### PR TITLE
Apply px per unit in `pick_closest`/`pick_sorted`

### PR DESCRIPTION
**Pull request by EdsterG**
# Description

Apply px per unit in `pick_closest`/`pick_sorted`. ~I haven't applied this change to GLMakie because I had some more questions about the suggestion in #4136.~ Instead of blocking #4136, I decided to open a separate PR for this fix.

Before this PR, PPU wasn't accounted for in `pick_closest`/`pick_sorted`. A `PPU < 1` would crash GLMakie and a `PPU > 1` would cause erroneous tooltip behavior in GLMakie/WGLMakie.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] Added an entry in CHANGELOG.md (for new features and breaking changes)

### CODE REVIEW

**Comment by EdsterG** [comment]
Referencing the suggestion from https://github.com/MakieOrg/Makie.jl/pull/4136#issuecomment-2293418017

```
# check xy in scene size...
x0, y0 = max.(1, floor.(Int, px_per_unit .* (xy .- range)))
x1, y1 = min.([w, h], ceil.(Int, px_per_unit .* (xy .+ range)))
dx = x1 - x0; dy = y1 - y0

# inline rect pick w/o applying px_per_unit again

x, y =  px_per_unit .* xy .+ 1 .- Vec2f(x0, y0)
# remaining distance calc + sorting as is
```

In pick sorted, `w, h = size(scene)` what are the units on these? If it's not pixels, `min.([w, h], ceil.(Int, px_per_unit .* (xy .+ range)))` won't work.

Inside pick native, `w, h = size(screen.root_scene)` are these units different from the ones in my previous question?

**Comment by EdsterG** [comment]
I pushed a commit based on some assumptions that I am not able to verify.

**Comment by ffreyer** [comment]
You can set px_per_unit with `display(fig, px_per_unit = ...)`

**Comment by EdsterG** [comment]
Pushed a few more fixes. Now the only open question I have is `scene` vs `screen.root_scene` in `pick_sorted`? Should I assert they're the same? If they are expected to differ sometimes, which one should I use? If they are expected to be the same, why the redundancy?

**Comment by EdsterG** [comment]
I've added a test that will fail without this fix. This PR is ready for review @ffreyer.

**Comment by ffreyer** [comment]
I think WGLMakie still has some issues with sorting. I've been testing with
```julia
begin
    scene = Scene(size = (400, 400))
    campixel!(scene)
    scatter!(scene, [100, 102, 102, 104, 104], [100, 102, 104, 102, 104])
    on(events(scene).mouseposition) do mp
        # sorted
        picks = Makie.pick_sorted(scene, mp, 50)
        N = length(picks)
        i = N > 0 ? picks[1][2] : nothing
        @info N, i

        # closest
        # plt, idx = Makie.pick(scene, mp, 50)
        # @info plt !== nothing
    end
    display(scene, px_per_unit = 2.71)
end
```

For `pick_sorted` you should see the index (i) changing as you move the cursor around the blob of markers, but I only see 5. I thought this might be because multiple plots end up with the same (default) distance but that doesn't seem to be the case.

pick_closest also doesn't print anything if I'm inside the WGLMakie window but outside the pick range. No idea why. Also wouldn't hold up the pr for this

**Comment by EdsterG** [comment]
Yeah, #4136 is important to fix the remaining WGLMakie issues. If you include the changes from the other PR, your example will work correctly.

**Comment by ffreyer** [comment]
If both prs are done I'd say we should recombine them so it's easier to review

**Comment by EdsterG** [comment]
> If both prs are done I'd say we should recombine them so it's easier to review

They're done from my perspective. I just haven't received much feedback on the other PR and though this fix is less "controversial", therefore I split to them to reduce friction. I'm also happy to re-combine if that'll help get them in faster.

**Comment by EdsterG** [comment]
Merged into #4136.

**Pull request closed without merging**
