### PR TITLE
Remove offset in `show_data` for `scatter`

### LINKED ISSUE #2724: Inspector: tooltip offset in `show_data` for `Scatter` assumes scalar `markersize`
Hovering over a point in the following scatter plot
```julia
p = scatter(Point.(rand(SVector{3,Float32}, 10)), markersize = [Vec2f(100*rand()) for _ in 1:10]); DataInspector(); p
```
errors with
```
Error in callback:
MethodError: no method matching +(::Vector{Vec2{Float64}}, ::Int64)

Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...)
   @ Base operators.jl:578
  +(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8}
   @ Base int.jl:87
  +(::Distributions.Cauchy, ::Real)
   @ Distributions ~/.julia/packages/Distributions/w3oji/src/univariate/continuous/cauchy.jl:104
  ...

Stacktrace:
 [1] show_data(inspector::DataInspector, plot::Scatter{Tuple{Vector{Point{2, Float32}}}}, idx::UInt32)
   @ Makie ~/.julia/packages/Makie/O4ktt/src/interaction/inspector.jl:504
```

The reason is that this line assumes that `plot.markersize[]` is a scalar, i.e. the same for all markers
https://github.com/MakieOrg/Makie.jl/blob/6e27645a476123f3e1a866cd4d453ac37a3f3de4/src/interaction/inspector.jl#L504

The purpose of that line is to shift the tooltip label a little bit away from the marker. 

In my opinion, this line should be simply removed. That would solve the present issue and would also makes the tooltip point more precisely to the hovered maker. For comparison, tooltips in `MeshScatter` do not apply such an offset to the tooltip. 

This is the tooltip with the current offset (using a scalar markersize):
Screenshot 2023-03-04 at 19 11 06

This is the tooltip without the offset (as proposed here)
Screenshot 2023-03-04 at 19 10 53

This is how `meshcatter` does it (no offset)
Screenshot 2023-03-04 at 19 11 34

### PR DESCRIPTION
**Pull request by pablosanjose**
# Description

Fixes #2724 

The tooltip offset in the `show_data` method for `scatter` plots (relevant when using `DataInspector`) is removed.
As it is in master, the offset assumes all markers to be of the same size, so it errors when that is not the case.
In contrast `meshscatter` uses no tooltip offset, and hence does not suffer from this issue. This PR brings `scatter` behavior in line with `meshscatter`. Arguably, the offset only makes the tooltip less precise spatially in busy plots, so this is also an improvement in tooltip clarity in my opinion.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

As a bugfix with no significant change in behavior, no additional actions apply, correct?

### CODE REVIEW

**Review by ffreyer — APPROVED** [review]
I added that bit because I thought it was nicer to be able to see the full marker. (Especially if it's something like an image scatter.) It's harder to get the same behavior with meshscatter because of 3D, so I didn't bother there. But this is ultimately just styling, you can argue either way so I'm fine with this change.

**Comment by SimonDanisch** [comment]
Should we make this configurable?

**Comment by ffreyer** [comment]
I guess we could? Something like
```julia
tt.offset[] = ifelse(a.should_offset_tooltip[], 0.5 * _offset_at(plot.markersize[], idx) + 2, a.offset[])
```
to reuse code from text layouting?

**Comment by pablosanjose** [comment]
@ffreyer, that could work, thanks for the suggestion. However, I'm not sufficiently familiar with the codebase to attempt adding a new `:should_offset_tooltip`, could you do this?

Note also that the approach used to deal with attribute vectors in some other places look like this:
https://github.com/MakieOrg/Makie.jl/blob/982a0b75702889b3a354c087551ca37aeb15567f/src/interaction/inspector.jl#L586

**Comment by ffreyer** [comment]
`_offset_at` wasn't general enough so I added and replaced it with `sv_getindex`. We can merge this once ci passes

**Comment by pablosanjose** [comment]
Marvellous, thank you @ffreyer!
How long would we need to wait, approx, to get a new release tag with this once it is merged?

**Comment by pablosanjose** [comment]
Oh, wait, this still fails:
```
p = scatter(Point.(rand(SVector{2,Float32}, 10)), markersize = [Vec2f(100*rand()) for _ in 1:10]); DataInspector(); p
```

We need to admit `Vector{<:Vec2f}` for markersize too, right?

**Comment by SimonDanisch** [comment]
>Oh, wait, this still fails:

Oh :D Can we fix this in a new PR?

**Comment by pablosanjose** [comment]
No, don't worry, the last commit I pushed fixes that too. T'is all good. Just looking forward to a tag to use this in a dependent project :-)

**Pull request merged**
