### PR TITLE
Fix CairoMakie mesh overflow

### PR DESCRIPTION
**Pull request by jkrumbiegel**
# Description

Fixes https://github.com/MakieOrg/Makie.jl/issues/2454

It seems that just adding patches to a single pattern causes an overflow at some point, corrupting Cairo's internals.
For bitmaps, it should make no difference if each triangle is drawn with a separate patch, because these aren't anti-aliased anyway so they can be drawn sequentially without problem. I'm not sure if the file size of vector graphics containing these will be higher, but in that case one could probably still flatten to a single bitmap by setting `rasterize = true` to the `surface` call.

## Type of change

Delete options that do not apply:

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] Added an entry in NEWS.md (for new features and breaking changes)
- [ ] Added or changed relevant sections in the documentation
- [ ] Added unit tests for new algorithms, conversion methods, etc.
- [ ] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

**Comment by fatteneder** [comment]
This does not eliminate the `out of memory` error entirely, or?
If I run the MWE from #2454 with an even much higher resolution then this could happen again, or?

Would it make sense to figure out this 'limit' and put a check in like we have it images/heatmaps?

**Comment by jkrumbiegel** [comment]
The higher the mesh resolution the less likely the bug I think. It's either due to number of patches within pattern (fixed completely if true) or due to pattern surface area (could still be hit with a super large triangle I guess?)

**Comment by fatteneder** [comment]
I tested the MWE with `Nx, Ny = 5000, 5000` and it works now.

But I also saw silent crashes of julia with `Nx, Ny = 8000`. However, that happened also with `GLMakie` (although with higher `N`s), likely because I ran out of RAM and swap (only using 8GB + 8GB atm).

**Comment by jkrumbiegel** [comment]
Yeah that sounds like a different issue again I think, I'm going to merge this one and we can open another issue for the other crashes.

**Pull request merged**
