### PR TITLE
Hook up ticksize attribute for Axis3

### PR DESCRIPTION
**Pull request by fatteneder**
# Description

Implements #2339

MWE
```julia
using GLMakie
GLMakie.activate!()
f = Figure()
ax3 = Axis3(f[1,1], xticksize=0.03, yticksize=0.07, zticksize=0.15)
meshscatter!(ax3, rand(10),rand(10),rand(10), label="test")
display(f)
```

image

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [ ] Added an entry in NEWS.md (for new features and breaking changes)

### CODE REVIEW

**Comment by jkrumbiegel** [comment]
Thanks for getting this rolling :) the thing is that you hooked up an implementation that I didn't want to keep, because it's just a hack to get ok looking ticks by default   as the ticks are tied to the axis length. This way I could draw them in data coordinates. But really, they should be drawn in screen coordinates so we can give them proper screen based lengths which are then comparable to Axis.
You'd have to project the direction vectors into screen space and then scale them to the chosen length in that space, plotting them with `space = :pixel` which we didn't have at the time I wrote Axis3.

**Comment by fatteneder** [comment]
I swear I read your comment in the issue ... but then I must have become too excited once I figured out where to put the ticksize, so I ignored it hahaha :)

I can take a look at that over the weekend.

**Comment by jkrumbiegel** [comment]
No worries, it would be cool if you could get it to work! The Axis3 code is always a bit more complex because of the three dimensions plus rotations that mean you have to think more abstractly about where things end up visually..

**Comment by fatteneder** [comment]
I pushed something that works locally for me. I kicked out the `to_topscene_2d_z` part, but not sure if that is ok.

**Comment by jkrumbiegel** [comment]
Seems to work well! What's the 10000 constant in there? I don't remember why I set the z the way I did at the time, even with the comment explaining it. Maybe it was just for the case when the ticks go inward, otherwise the plot shouldn't overlap them no?

**Comment by jkrumbiegel** [comment]
And I think the `space = :pixel` is not necessary after all because the topscene is already a `campixel` one

**Comment by fatteneder** [comment]
The `-100000` is needed so that ticks appear behind any plotted objects.
The comment is just taken here: https://github.com/MakieOrg/Makie.jl/pull/2354/files#diff-02aae39f0699056656ef21e70988c3494ef3378c0f2eb1b655f8e1ea0cb2b048R452-R459


> And I think the space = :pixel is not necessary after all because the topscene is already a campixel one

Ok, I can fix that later.

**Comment by fatteneder** [comment]
image

I think the tick placement needs more tuning, because if you look close you can see that the ticks don't exactly align with the grid lines (the x ticks show the biggest difference).

This issue was already there before this PR. I could not figure out the problem right now. I will have to take a closer look again tomorrow.

**Comment by fatteneder** [comment]
> I will have to take a closer look again tomorrow.

Sorry for the delay, but I was busy in the past week ...

I took at look this again. I checked that the endpoints of the grid lines agree with the ends of the tick lines we draw -- they are correct.
Right now I suspect that the issue is in `Makie.project`. In particular, if I change here https://github.com/MakieOrg/Makie.jl/blob/e0cb40096896c3f43a390cd0523138ad644e41fc/src/camera/projection_math.jl#L300-L306 the last line to
```julia
return (((p .+ 1f0) ./ 2f0) .* (resolution .- 1f0)) .+ 0.5f0
```
then things look much better:

- before
ticks bad

- after
ticks good


Q: What is the logic behind this line? I am having a difficult time determining whether this is the problem or not.

**Comment by jkrumbiegel** [comment]
Huh I feel like I debugged a similar off by a pixel projection bug in CairoMakie a long time ago. 
But shouldn't we have seen the same problem in other places too if this was the case?

**Comment by jkrumbiegel** [comment]
Maybe the grid lines are just moved down a tiny bit, I did something like that to improve z fighting issues but maybe I just moved the panels back a little bit and not the grid lines.

**Comment by fatteneder** [comment]
> Maybe the grid lines are just moved down a tiny bit

That was also my first idea.
But from what I can tell, ticks and grid lines are both plotted with `linesegments`. Becaues of that I compared their (3d) endpoints and they agree exactly.

Regarding the `z` shift: We only apply the -10000 z shift to the ticks. But removing it does not change anything.

**Comment by fatteneder** [comment]
> Huh I feel like I debugged a similar off by a pixel projection bug in CairoMakie a long time ago.

I couldn't find an issue or PR in this repo, but I would like to see what your reasoning was there back then. Could you maybe try to dig it up for me?

**Comment by SimonDanisch** [comment]
This seems like its not a regression, so I think it shouldn't hold up merging the PR!

**Comment by jkrumbiegel** [comment]
yeah if that's the only thing, let's merge for now

**Pull request merged**
