### PR TITLE
Default to `px_per_unit=2` in CairoMakie

### PR DESCRIPTION
**Pull request by ericphanson**
# Description

1 is way too blurry in my opinion. I generally use `px_per_unit=8` but the file sizes get a bit large, so I figured 2 was less controversial.

## Type of change

Delete options that do not apply:

- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [ ] Added an entry in NEWS.md (for new features and breaking changes)
- [ ] Added or changed relevant sections in the documentation
- [ ] Added unit tests for new algorithms, conversion methods, etc.
- [ ] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

**Comment by ffreyer** [comment]
You can also set a resolution directly in `Figure`. With `px_per_unit = 2` the final image would be twice the size you set, which seems like a weird default to me. It would also make the size different between backends

**Comment by ericphanson** [comment]
Ah ok, maybe this approach is not right then. Perhaps the default resolution should be higher instead? I'm not really sure, I just know "blurry plots [when viewed on high-resolution screens] by default" doesn't seem ideal.

**Comment by Moelf** [comment]
What background? CairoMakie can produce svg which shouldn't be blur?

**Comment by ericphanson** [comment]
it can; CairoMakie produces PNGs by default, which I think is fine; high density SVGs can be a big perf cliff for IDEs, saving to disk etc (every single point gets serialized so if you have a massive scatter plot, you have a massive file). So I think PNGs by default is a reasonable choice. PNGs are also supported by more software, so it makes it more portable/usable.

One can do `CairoMakie.activate!(; px_per_unit=8)` (or whatever value they want) to change it globally, or set the resolution in the `Figure`, or set the scaling at `save` time, or use SVGs. So there's definitely *options* to improve things. 

So my gripe here is just about the default settings.

**Comment by Moelf** [comment]
svg is best for publication, and I think having massive amount of scattered points is, rare? why not use 2d histogram...

**Comment by ericphanson** [comment]
sure, which is why folks should use SVG for publications? That doesn't mean it should be the default.

A massive amount of points is somewhat rare, and a scatter plot of them is not optimal. The problem is that if you do plot a scatter w a massive number of points (e.g. due to a typo or not realizing) it can crash or hang your julia session, browser, or ide, depending on what goes wrong. That's a bad enough thing that it shouldn't be the default, IMO. Also, apparently it had other quirks, discussed in the PR which changed the default to PNG: https://github.com/JuliaPlots/CairoMakie.jl/pull/147.

**Comment by jkrumbiegel** [comment]
I also always increase the px_per_unit when I use CairoMakie, so I'm in principle open to a higher value there. The problem is that you cannot set pixel density metadata on an image in a way that would be respected by IDEs / webapps like Pluto.

When you display a plot with the `image/png` mime type, the png image data is written out as a blob and pasted in some `` tag in the output cell / plot pane. But, and that's the reason for the default setting of 1, if the Figure had resolution 800x600 and px_per_unit is 2, then the output image will take 1600x1200 css pixels of space (if it's available). So on retina displays it will still be blurry, as it still uses 4 native pixels per image pixel / css pixel.

At some point the viewer space will run out and the image will not get larger anymore, only at that point do you get pixel density improvement or less effective blurriness on your screen. But this only works if you don't have enough space, which may or may not be the case.

So my preferred solution for the future, which isn't perfectly implemented yet, is to use the html mime type for output. Then we can write `` so the image will always have the correct base size, just using a higher pixel density.

**Comment by jkrumbiegel** [comment]
Compare with https://github.com/MakieOrg/Makie.jl/issues/2264

**Comment by Moelf** [comment]
do the viewer in e.g. VS Code respect this:
https://www.w3.org/TR/2003/REC-PNG-20031110/#11pHYs

?

**Comment by jkrumbiegel** [comment]
No, basically nothing respects density metadata, aside from maybe Photoshop and similar tools.

**Comment by Moelf** [comment]
since we (Julia) writes the viewer panel, can we not support it?

**Comment by jkrumbiegel** [comment]
it's not a scalable solution if it only works in vscode :)

**Comment by Moelf** [comment]
fine, blurry then.

**Comment by jkrumbiegel** [comment]
With the html thing I'm proposing it wouldn't be blurry

**Pull request closed without merging**
