### PR TITLE
More improvements for ReferenceUpdater

### PR DESCRIPTION
**Pull request by ffreyer**
# Description

Changes:
- [x] pick latest CI run if multiple are present (e.g. due to closing and reopening a pr)
- [x] add tab for removing reference images of missing recordings (e.g. to clean up reference images for renamed or deleted tests)
- [x] Use latest reference images when updating, rather than the ones bundled with the CI run. This should prevent reference images from getting overwritten for outdated CI runs. ~~make ReferenceUpdater safe to use from an outdated CI run (currently this uses old reference images from the CI run, rather than the latest uploaded ones.)~~
- [x] use table layout for new (and missing) ref images
- [x] add some documentation to the page
- [x] add a "toggle all" for added and removed refimgs

## Type of change

- tooling

### CODE REVIEW

**Comment by jkrumbiegel** [comment]
> make ReferenceUpdater safe to use from an outdated CI run (currently this uses old reference images from the CI run, rather than the latest uploaded ones.

Yeah that's currently not great that you can clobber already updated reference images with the old ones from a previous CI run. I did this at the time because I was focusing on showing the changes that CI picked up in that specific run (that's what the scores were computed for etc.). How did you want to change this, compute scores again against the freshly downloaded reference set?

**Comment by ffreyer** [comment]
Updating should not download the lastest refimg set and merge with that, instead of using the one attached to a pr.

The page now looks like this: (at 80% zoom to fit more on a screenshot)
grafik

**Review by jkrumbiegel — APPROVED** [review]
Maybe take out the couple `console.log`s if they aren't needed, otherwise this looks good to me!

**Comment by ffreyer** [comment]
Oh I forgot about those

**Pull request merged**
