### PR TITLE
Allow `width` to be set per box in `boxplot`

### PR DESCRIPTION
**Pull request by EdsterG**
# Description

Allows width to be set per box. Not sure if this is a bug fix or new feature, classified it as a bug fix since colors can be set per box.

This also fixes `boxplot` when `range` is zero. Before this PR nothing would get plotted (because the color vector was empty), after this PR the plot works correctly with zero range.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] Added an entry in CHANGELOG.md (for new features and breaking changes)
- [ ] Added or changed relevant sections in the documentation
- [ ] Added unit tests for new algorithms, conversion methods, etc.
- [ ] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

**Comment by EdsterG** [comment]
This PR is good to go on my end. Would like to add a test but it overlaps with #4433. How would you like to coordinate it @ffreyer? Can ether wait for #4433 to get merged, OR if this PR is merged before, #4433 can easily be updated to test width, e.g. `WGLMakie.boxplot(fig[1, 1], categories, values, width = categories ./ 3)`.

**Comment by EdsterG** [comment]
Why do the tests fail on scatter? I thought that was fixed and RNG stabilized?

**Comment by EdsterG** [comment]
Nice, thanks for fixing these test issues and for adding all of the new tests.

**Comment by EdsterG** [comment]
@ffreyer I've updated the ref image tests to include variable width per category, just needs an update to the ref images. If I understood correctly, only maintainers can update the ref images?

**Comment by ffreyer** [comment]
Thanks for updating. I uploaded the new refimages and the remaining failure is unrelated to this pr so I'm merging this.

**Pull request merged**
