### PR TITLE
fix: make `space` work for BarPlot

### PR DESCRIPTION
**Pull request by EdsterG**
# Description

Makes BarPlot work with the `space` attribute.

Side note, the current approach to forwarding parameters seems very error prone. Are there any thoughts/prototypes to automate parameter passing?

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] Added an entry in CHANGELOG.md (for new features and breaking changes)
- [ ] Added or changed relevant sections in the documentation
- [ ] Added unit tests for new algorithms, conversion methods, etc.
- [ ] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

**Comment by EdsterG** [comment]
Found the prototype, this PR is made obsolete by #4399. If there's no plan to merge #4399 soon, let's get this patch in?

**Comment by EdsterG** [comment]
Thanks for the fix, I had a local commit with the same typo, guess I cherry picked the wrong one.

**Comment by EdsterG** [comment]
@SimonDanisch shall we merge this, given how trivial the change is?

**Review by ffreyer — APPROVED** [review]
I'd be fine with that

**Pull request merged**
