### PR TITLE
Standardize view and projection matrices

### PR DESCRIPTION
**Pull request by ffreyer**
# Description

This prepares some things for #3226:
- move translations from projection to view matrices
- track eyeposition in Axis and PolarAxis
- rework Axis3 to use `perspectiveprojection` and `lookat` without modification (though I split up `lookat` into two steps)
- add inv(::Quaternion)

And some random minor cleanup of Axis3 docs (indention, wrong render order in W/GLMakie, double-plotting of Label) + camera controller (name change).

<details>
<summary>Axis3 comparsion</summary>

Axis3 has more extensive changes so things could be different. Here are some new vs old comparisons with docs:

 #### Aspect

Screenshot from 2024-01-13 14-39-03

Screenshot from 2024-01-13 14-39-03

#### Viewing angles

Screenshot from 2024-01-13 14-41-01

Tick placement seems to be slightly different (e.g. bottom left z is cut off more, top left z's overlap more(?))

Screenshot from 2024-01-13 14-41-35

Slightly less space to the title here as well

#### Perspectiveness

Screenshot from 2024-01-13 14-42-26

#### viewmodes

Screenshot from 2024-01-13 14-50-56

Also checked this with `perspectiveness = 0.6`, no visible changes.

#### Tight frustum testing/debugging

This will show you the generated frustum (i.e. what area of the scene will be rendered) with th view space bounding box (+ bounding sphere for :fit) of the Axis3.

```julia
using GeometryBasics

function camera_debug(gridpos, ax::Axis3)
    function frustum_snapshot(cam)
        r = Rect3f(Point3f(-1, -1, -1), Vec3f(2, 2, 2))
        rect_ps = coordinates(r) .|> Point3f
        insert!(rect_ps, 13, Point3f(1, -1, 1)) # fix bad line

        inv_pv = inv(cam.projectionview[])
        return map(rect_ps) do p
            p = inv_pv * to_ndim(Point4f, p, 1)
            return p[Vec(1,2,3)] / p[4]
        end
    end

    scene = ax.scene
    cam = scene.camera
    frustum = map(pv -> frustum_snapshot(cam), cam.projectionview)

    scene2 = LScene(gridpos, show_axis = false)

    _cc = Makie.Camera3D(
        scene2.scene, projectiontype = Makie.Orthographic,
        near = 0.001f0, far = 1000.0f0, clipping_mode = :static
    )
    lines!(scene2, frustum, color = :blue, linestyle = :dot)

    # bbox is Axis3 specific
    bbox = ax.finallimits
    model = ax.scene.transformation.model
    bb = map(model, bbox) do model, bb
        ps = [(model * to_ndim(Point4f, p, 1))[Vec(1,2,3)] for p in Makie.corners(bb)]
        Rect3f(ps)
    end
    r = map(bb -> maximum(norm.(Makie.corners(bb))), bb)

    linesegments!(scene2, bb, color = :black)
    wireframe!(scene2, map(r -> Sphere(Point3f(0), r), r), color = (:black, 0.2), transparency = true)
    # scatter!(scene2, scene.camera.eyeposition, color = :red)
    scatter!(scene2, Point3f(0), color = :blue)

    r = map(frustum) do frustum
        ps = vcat(frustum[1:12], frustum[14:end])
        normal_mesh(ps, faces(Rect3f()))
    end
    mesh!(scene2, r, color = (:red, 0.3), fxaa = false, transparency = true)
    notify(frustum)

    return scene2
end

begin
    fig = Figure()

    # show the extent of each cell using a box
    b = Box(fig[1, 1], strokewidth = 0, color = :gray95)
    translate!(b.blockscene, Vec3f(0, 0, -10_000))

    ax = Axis3(
        fig[1, 1]; viewmode = :stretch, protrusions = 0,
        aspect = (1,2,3), perspectiveness = 0.5
    )
    hidedecorations!(ax)
    camera_debug(fig[1, 2], ax)
    fig
end
```

</details>

## Type of change

- [x] internal adjustments 

## Checklist

- ~~Added an entry in NEWS.md (for new features and breaking changes)~~
- ~~Added or changed relevant sections in the documentation~~
- [x] Added unit tests for new algorithms, conversion methods, etc.
- ~~Added reference image tests for new plotting functions, recipes, visual options, etc.~~

### CODE REVIEW

**Comment by ffreyer** [comment]
`space 3D` failing is expected because the near and far planes are now tight to the `finallimits` in Axis3. This should also change OIT there, but I don't think we explicitly test that.

**Comment by asinghvi17** [comment]
Were these changes merged in 0.21?

**Comment by ffreyer** [comment]
No they weren't. 

This came from a thought that we'd implement Float32 scaling based on the model, view and projection matrix, i.e. independently of limits which aren't known by the backend. A consistent structure for those matrices would have been useful for that.

Now this is less important but maybe still useful as a clean up. I.e. maybe it's easier to follow what Axis3 does camera wise after this. It might also be the case that some lighting calculation or SSAO makes some assumptions about camera matrices that aren't true without this (i.e. transpose = inv).

**Comment by ffreyer** [comment]
> `space 3D` failing is expected because the near and far planes are now tight to the `finallimits` in Axis3. This should also change OIT there, but I don't think we explicitly test that.

Still true

**Pull request closed without merging**
