### PR TITLE
Clean up colormap handling and implement colorscale + alpha kw

### PR DESCRIPTION
**Pull request by SimonDanisch**
Continuation of #colorscale https://github.com/MakieOrg/Makie.jl/pull/2493

### CODE REVIEW

**Comment by t-bltg** [comment]
Bump, we really need this in our lab.

**Comment by tomchor** [comment]
> Bump, we really need this in our lab.

Same! Eager to be able to use this! :)

I'm also willing to help with testing, etc., if at all helpful.

**Comment by SimonDanisch** [comment]
Alright, this PR is ready to try out + review!
The tests only fail, since this PR actually fixes a bug with Volume, where it was always using `(0, 1)` as colorrange if not specified differently.

**Comment by tomchor** [comment]
Hmm, I'm getting an error `using GLMakie` on a temp environment. Am I missing something?:

```julia
(twake) pkg> activate --temp
  Activating new project at `/tmp/jl_4a3sdZ`

(jl_4a3sdZ) pkg> add GLMakie#sd/colormaps
    Updating git-repo `https://github.com/MakieOrg/Makie.jl.git`
   Resolving package versions...
    Updating `/tmp/jl_4a3sdZ/Project.toml`
  [e9467ef8] + GLMakie v0.8.6 `https://github.com/MakieOrg/Makie.jl.git:GLMakie#sd/colormaps`
    Updating `/tmp/jl_4a3sdZ/Manifest.toml`
  [621f4979] + AbstractFFTs v1.4.0
# ... a bunch of packages being installed ...
  [3f19e933] + p7zip_jll v17.4.0+0
        Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated -m`
Precompiling project...
  ✗ GLMakie
  0 dependencies successfully precompiled in 20 seconds. 206 already precompiled.
  1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package

julia> using GLMakie
[ Info: Precompiling GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a]
ERROR: LoadError: KeyError: key :calculated_colors not found
Stacktrace:
  [1] getindex(h::Dict{Symbol, Observables.Observable}, key::Symbol)
    @ Base ./dict.jl:484
  [2] getindex
    @ ~/.julia/packages/MakieCore/6sckc/src/attributes.jl:91 [inlined]
  [3] getindex(x::MakieCore.Mesh{Tuple{GeometryBasics.Mesh{2, Float32, GeometryBasics.Ngon{2, Float32, 3, GeometryBasics.Point{2, Float32}}, GeometryBasics.SimpleFaceView{2, Float32, 3, GeometryBasics.OffsetInteger{-1, UInt32}, GeometryBasics.Point{2, Float32}, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}}}}, key::Symbol)
    @ MakieCore ~/.julia/packages/MakieCore/6sckc/src/attributes.jl:187
  [4] getproperty
    @ ~/.julia/packages/MakieCore/6sckc/src/attributes.jl:78 [inlined]
  [5] handle_intensities!(attributes::Dict{Symbol, Any}, plot::MakieCore.Mesh{Tuple{GeometryBasics.Mesh{2, Float32, GeometryBasics.Ngon{2, Float32, 3, GeometryBasics.Point{2, Float32}}, GeometryBasics.SimpleFaceView{2, Float32, 3, GeometryBasics.OffsetInteger{-1, UInt32}, GeometryBasics.Point{2, Float32}, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}}}})
    @ GLMakie ~/.julia/packages/GLMakie/Csnzm/src/drawing_primitives.jl:74
  [6] (::GLMakie.var"#177#180"{GLMakie.var"#255#256"{GLMakie.Screen{GLFW.Window}, MakieCore.Mesh{Tuple{GeometryBasics.Mesh{2, Float32, GeometryBasics.Ngon{2, Float32, 3, GeometryBasics.Point{2, Float32}}, GeometryBasics.SimpleFaceView{2, Float32, 3, GeometryBasics.OffsetInteger{-1, UInt32}, GeometryBasics.Point{2, Float32}, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}}}}}, GLMakie.Screen{GLFW.Window}, Makie.Scene, MakieCore.Mesh{Tuple{GeometryBasics.Mesh{2, Float32, GeometryBasics.Ngon{2, Float32, 3, GeometryBasics.Point{2, Float32}}, GeometryBasics.SimpleFaceView{2, Float32, 3, GeometryBasics.OffsetInteger{-1, UInt32}, GeometryBasics.Point{2, Float32}, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}}}}})()
    @ GLMakie ~/.julia/packages/GLMakie/Csnzm/src/drawing_primitives.jl:132
  [7] get!(default::GLMakie.var"#177#180"{GLMakie.var"#255#256"{GLMakie.Screen{GLFW.Window}, MakieCore.Mesh{Tuple{GeometryBasics.Mesh{2, Float32, GeometryBasics.Ngon{2, Float32, 3, GeometryBasics.Point{2, Float32}}, GeometryBasics.SimpleFaceView{2, Float32, 3, GeometryBasics.OffsetInteger{-1, UInt32}, GeometryBasics.Point{2, Float32}, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}}}}}, GLMakie.Screen{GLFW.Window}, Makie.Scene, MakieCore.Mesh{Tuple{GeometryBasics.Mesh{2, Float32, GeometryBasics.Ngon{2, Float32, 3, GeometryBasics.Point{2, Float32}}, GeometryBasics.SimpleFaceView{2, Float32, 3, GeometryBasics.OffsetInteger{-1, UInt32}, GeometryBasics.Point{2, Float32}, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}}}}}, h::Dict{UInt64, GLMakie.GLAbstraction.RenderObject}, key::UInt64)
    @ Base ./dict.jl:468
  [8] cached_robj!(robj_func::GLMakie.var"#255#256"{GLMakie.Screen{GLFW.Window}, MakieCore.Mesh{Tuple{GeometryBasics.Mesh{2, Float32, GeometryBasics.Ngon{2, Float32, 3, GeometryBasics.Point{2, Float32}}, GeometryBasics.SimpleFaceView{2, Float32, 3, GeometryBasics.OffsetInteger{-1, UInt32}, GeometryBasics.Point{2, Float32}, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}}}}}, screen::GLMakie.Screen{GLFW.Window}, scene::Makie.Scene, x::MakieCore.Mesh{Tuple{GeometryBasics.Mesh{2, Float32, GeometryBasics.Ngon{2, Float32, 3, GeometryBasics.Point{2, Float32}}, GeometryBasics.SimpleFaceView{2, Float32, 3, GeometryBasics.OffsetInteger{-1, UInt32}, GeometryBasics.Point{2, Float32}, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}}}})
    @ GLMakie ~/.julia/packages/GLMakie/Csnzm/src/drawing_primitives.jl:103
  [9] draw_atomic
    @ ~/.julia/packages/GLMakie/Csnzm/src/drawing_primitives.jl:538 [inlined]
 [10] insert!(screen::GLMakie.Screen{GLFW.Window}, scene::Makie.Scene, x::MakieCore.Mesh{Tuple{GeometryBasics.Mesh{2, Float32, GeometryBasics.Ngon{2, Float32, 3, GeometryBasics.Point{2, Float32}}, GeometryBasics.SimpleFaceView{2, Float32, 3, GeometryBasics.OffsetInteger{-1, UInt32}, GeometryBasics.Point{2, Float32}, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}}}})
    @ GLMakie ~/.julia/packages/GLMakie/Csnzm/src/drawing_primitives.jl:151
 [11] (::GLMakie.var"#183#184"{GLMakie.Screen{GLFW.Window}, Makie.Scene})(x::MakieCore.Mesh{Tuple{GeometryBasics.Mesh{2, Float32, GeometryBasics.Ngon{2, Float32, 3, GeometryBasics.Point{2, Float32}}, GeometryBasics.SimpleFaceView{2, Float32, 3, GeometryBasics.OffsetInteger{-1, UInt32}, GeometryBasics.Point{2, Float32}, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}}}})
    @ GLMakie ~/.julia/packages/GLMakie/Csnzm/src/drawing_primitives.jl:156
 [12] foreach(f::GLMakie.var"#183#184"{GLMakie.Screen{GLFW.Window}, Makie.Scene}, itr::Vector{MakieCore.AbstractPlot})
    @ Base ./abstractarray.jl:3073
 [13] insert!(screen::GLMakie.Screen{GLFW.Window}, scene::Makie.Scene, x::MakieCore.Poly{Tuple{GeometryBasics.HyperRectangle{2, Int64}}})
    @ GLMakie ~/.julia/packages/GLMakie/Csnzm/src/drawing_primitives.jl:153
 [14] insertplots!(screen::GLMakie.Screen{GLFW.Window}, scene::Makie.Scene)
    @ GLMakie ~/.julia/packages/GLMakie/Csnzm/src/screen.jl:448
 [15] insertplots!(screen::GLMakie.Screen{GLFW.Window}, scene::Makie.Scene)
    @ GLMakie ~/.julia/packages/GLMakie/Csnzm/src/screen.jl:451
 [16] display_scene!(screen::GLMakie.Screen{GLFW.Window}, scene::Makie.Scene)
    @ GLMakie ~/.julia/packages/GLMakie/Csnzm/src/screen.jl:380
 [17] GLMakie.Screen(scene::Makie.Scene, config::GLMakie.ScreenConfig, ::Makie.ImageStorageFormat; start_renderloop::Bool)
    @ GLMakie ~/.julia/packages/GLMakie/Csnzm/src/screen.jl:415
 [18] GLMakie.Screen(scene::Makie.Scene, config::GLMakie.ScreenConfig, ::Makie.ImageStorageFormat)
    @ GLMakie ~/.julia/packages/GLMakie/Csnzm/src/screen.jl:411
 [19] getscreen(backend::Module, scene::Makie.Scene, args::Makie.ImageStorageFormat; screen_config::Base.Pairs{Symbol, Bool, Tuple{Symbol, Symbol}, NamedTuple{(:start_renderloop, :visible), Tuple{Bool, Bool}}})
    @ Makie ~/.julia/packages/Makie/iECbF/src/display.jl:400
 [20] getscreen
    @ ~/.julia/packages/Makie/iECbF/src/display.jl:383 [inlined]
 [21] colorbuffer(fig::Makie.FigureAxisPlot, format::Makie.ImageStorageFormat; update::Bool, backend::Module, screen_config::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Makie ~/.julia/packages/Makie/iECbF/src/display.jl:421
 [22] colorbuffer
    @ ~/.julia/packages/Makie/iECbF/src/display.jl:418 [inlined]
 [23] colorbuffer(fig::Makie.FigureAxisPlot)
    @ Makie ~/.julia/packages/Makie/iECbF/src/display.jl:418
 [24] top-level scope
    @ ~/.julia/packages/GLMakie/Csnzm/src/precompiles.jl:7
 [25] include(mod::Module, _path::String)
    @ Base ./Base.jl:457
 [26] include
    @ ~/.julia/packages/GLMakie/Csnzm/src/GLMakie.jl:1 [inlined]
 [27] macro expansion
    @ ~/.julia/packages/GLMakie/Csnzm/src/precompiles.jl:23 [inlined]
 [28] macro expansion
    @ ~/.julia/packages/PrecompileTools/0yi7r/src/workloads.jl:74 [inlined]
 [29] macro expansion
    @ ~/.julia/packages/GLMakie/Csnzm/src/precompiles.jl:16 [inlined]
 [30] macro expansion
    @ ~/.julia/packages/PrecompileTools/0yi7r/src/workloads.jl:136 [inlined]
 [31] top-level scope
    @ ~/.julia/packages/GLMakie/Csnzm/src/precompiles.jl:14
 [32] include(mod::Module, _path::String)
    @ Base ./Base.jl:457
 [33] include(x::String)
    @ GLMakie ~/.julia/packages/GLMakie/Csnzm/src/GLMakie.jl:1
 [34] top-level scope
    @ ~/.julia/packages/GLMakie/Csnzm/src/GLMakie.jl:59
 [35] include
    @ ./Base.jl:457 [inlined]
 [36] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
    @ Base ./loading.jl:2045
 [37] top-level scope
    @ stdin:3
in expression starting at /home/tomas/.julia/packages/Makie/iECbF/precompile/shared-precompile.jl:4
in expression starting at /home/tomas/.julia/packages/GLMakie/Csnzm/src/precompiles.jl:13
in expression starting at /home/tomas/.julia/packages/GLMakie/Csnzm/src/GLMakie.jl:1
in expression starting at stdin:3
ERROR: Failed to precompile GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a] to "/home/tomas/.julia/compiled/v1.9/GLMakie/jl_ihwAjU".
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
   @ Base ./loading.jl:2296
 [3] compilecache
   @ ./loading.jl:2163 [inlined]
 [4] _require(pkg::Base.PkgId, env::String)
   @ Base ./loading.jl:1805
 [5] _require_prelocked(uuidkey::Base.PkgId, env::String)
   @ Base ./loading.jl:1660
 [6] macro expansion
   @ ./loading.jl:1648 [inlined]
 [7] macro expansion
   @ ./lock.jl:267 [inlined]
 [8] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1611
```

**Comment by SimonDanisch** [comment]
yes you also need to checkout makie and makiecore

**Comment by tomchor** [comment]
> yes you also need to checkout makie and makiecore

Thanks! I thought those were automatically pulled using a fresh env, but I guess not. Some things I tested from https://github.com/MakieOrg/Makie.jl/pull/2493:

```julia
using GLMakie
import Random
Random.seed!(123)
x = y = 1:100;
z = rand(1:100, 100, 100);
fig = Figure();
ax = Axis(fig[1, 1], aspect=1, xscale=log10, yscale=log10);
hm = heatmap!(ax, x, y, z; colormap=:gist_stern, colorscale=log10);  # NOTE: added `colorscale` attr
Colorbar(fig[1, 2], hm);  # inherits `scale = p.colorscale` by default
display(fig)
Makie.save("stern.png", fig)
fig
```

image

Looks [exactly like it should](https://github.com/MakieOrg/Makie.jl/pull/2493#issuecomment-1363397643). Same thing when using `CairoMakie`.

---

Code:

```julia
using CairoMakie
x = randn(10_000);
y = randn(10_000);
fig = Figure();
hexbin(fig[1, 1], x, y; bins = 40, axis = (aspect = DataAspect(), title = "scale = identity"));
hexbin(fig[1, 2], x, y; bins = 40,  axis = (aspect = DataAspect(), title = "colorscale = log10"), colorscale = log10);
display(fig)
save("hexb.png", fig)
```

Result:

display

---

Code:

```julia
using CairoMakie
xs = range(0, 10; length = 30);
ys = 0.5 .* sin.(xs);
markersize = range(5, 30; length = 30);
color = 1:30;
fig = Figure();
scatter(fig[1, 1], xs, ys; markersize, color, colorscale = identity);
scatter(fig[2, 1], xs, ys; markersize, color, colorscale = log10);
display(fig)
save("scatter.png", fig)
```

Result:

display

---

Code:

```julia
x = y = range(-1, 1; length = 20);
f(x, y) = exp(-(x^2 + y^2)^2);
fig = Figure();
surface(fig[1, 1], x, y, f; colorscale = identity);
surface(fig[1, 2], x, y, f; colorscale = log10);
display(fig)
save("surface.png", fig)
```

Result:

image

I tested some other code but to keep this brief: everything I tested from https://github.com/MakieOrg/Makie.jl/pull/2493 worked well. I also tested a few of my own production scripts for animations with this branch everything worked like a charm :+1: 

Thanks @SimonDanisch! Hoping this gets merged soon :crossed_fingers:

**Comment by t-bltg** [comment]
I've also tested the examples of https://github.com/MakieOrg/Makie.jl/pull/2493, and also the specific interactive issues pointed out in https://github.com/MakieOrg/Makie.jl/pull/2493#issuecomment-1468417488: I haven't observed any regression, great work !

I also hope we can get this PR soon in master :)

**Comment by SimonDanisch** [comment]
I mainly need to check the colorbar with highclip etc, and if that turns out fine I think we can merge... maybe we'll also need a few more tests!

**Comment by t-bltg** [comment]
> maybe we'll also need a few more tests!

I think the more we can test this PR for corner cases the better, so @tomchor, if you have any reduced examples from your production codes that we didn't think of, they would be very welcome in this PR.

**Comment by tomchor** [comment]
> > maybe we'll also need a few more tests!
> 
> I think the more we can test this PR for corner cases the better, so @tomchor, if you have any reduced examples from your production codes that we didn't think of, they would be very welcome in this PR.

All my production code is actually pretty simple in the use of logscale. The only difference that I didn't see tested before (which is why I wanted to test my code) is that I use for recording animations with the cairo backend.

**Comment by SimonDanisch** [comment]
interactions with colorbar etc is currently the most untrlested..

**Comment by SimonDanisch** [comment]
I think this is ready to merge :)

**Comment by SimonDanisch** [comment]
To not make this breaking we should rather deprecate `hexbin.scale` instead of just removing it.

**Pull request merged**
