### PR TITLE
Change automatic color generation for Voronoiplot

### PR DESCRIPTION
**Pull request by DanielVandH**
# Description

Fixes https://github.com/MakieOrg/Makie.jl/issues/4344 by using a consistent method for generating colors. Using this approach the colors will be consistent between plots even if generators were removed or added. The old approach wasn't optimal since the `Set` defining `each_generator(vorn)` isn't ordered consistently across tessellations if the generator set changed.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] Added an entry in CHANGELOG.md (for new features and breaking changes)
- [x] Added or changed relevant sections in the documentation
- [x] Added unit tests for new algorithms, conversion methods, etc.
- [ ] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

**Comment by DanielVandH** [comment]
This PR breaks

Voronoiplot for a centroidal tessellation with an automatic colormap.png
Voronoiplot after adding points.png                                                           
Voronoiplot for a tessellation with a custom bounding box.png        

because of the new color generation method. I've checked them myself and nothing else is broken, it's just the colors. I don't see a consistent way to define the colors that is consistent with the colors generated by the previous method, so is just regenerating the images sufficient?

**Comment by ffreyer** [comment]
I think it's fine that the automatically chosen colors change, but it would mean that we consider this breaking and delay it until the next breaking release.

**Review by jkrumbiegel — APPROVED** [review]

**Comment by SimonDanisch** [comment]
I'm wondering if we can tag this as a patch version, considering that it's not that close to core Makie and the colors are somewhat arbitrary.
I guess I'd let @DanielVandH decide this.

**Comment by DanielVandH** [comment]
It would be nice to get it in earlier, but I don't mind waiting for another breaking release if you prefer . I would agree with you though that I don't think it's so breaking.

**Pull request closed without merging**
