### PR TITLE
`LineAxis`: add arbitrary `{x,y}labelrotation`

### PR DESCRIPTION
**Pull request by t-bltg**
Fix https://github.com/MakieOrg/Makie.jl/issues/1187.
Fix https://github.com/MakieOrg/Makie.jl/issues/2222.

# Description

As discussed with @jkrumbiegel on discord, add the ability to rotate axis labels:
```julia
julia> using CairoMakie
julia> fap = lines(0..2π, sin; axis = (; xlabel = "x", ylabel = "y", ylabelrotation = 0))
julia> save("sin.png", fap)
```
sin

Any comments on adding docs about this (where should this go ?) or tests (do you want static tests or new ref images maybe ?) would be appreciated.

TODO:

- [x] handle alignements

## Type of change

Delete options that do not apply:

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] Added an entry in NEWS.md (for new features and breaking changes)
- [ ] Added or changed relevant sections in the documentation
- [ ] Added unit tests for new algorithms, conversion methods, etc.
- [x] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

**Comment by fatteneder** [comment]
Closes https://github.com/MakieOrg/Makie.jl/issues/2222

**Comment by t-bltg** [comment]
For the alignements, I've reused (and renamed) the `calculate_real_ticklabel_align` routine, but is was coded for discrete rotation values, so it's not very suited to arbitrary rotation values.

Would it be acceptable to use `sin(rot)` and `cos(rot)` instead ?

**Comment by t-bltg** [comment]
So I've got this simple example.
```julia
julia> N = 18  # number of rotations
julia> fig, ax, _ = scatter(0:1; axis = (; xlabel = "a nice and long x label for this axis", ylabel = "a nice and long y label for this axis"))
julia> record(fig, "rot.gif") do io
        for rot in LinRange(0, 2π, N)
            ax.xlabelrotation[] = rot
            ax.ylabelrotation[] = rot
            recordframe!(io)
        end
    end
```
rot

Regarding the test I have a few questions:

- what is a `Stepper` and how is it used in the tests ? why a single `Makie.step!(st)` ?  
- what do we really want in terms of alignment ?

**Comment by jkrumbiegel** [comment]
Ok you can see in your example how the layout does not react to the different space taken up by the rotating labels. I would make the alignment behave like `Label` does when you set `rotation` on it, treat the whole thing like it takes up a rectangular box around the center of which it rotates.

**Comment by t-bltg** [comment]
I the alignment is set to `(:center, :center)`, where is the anchoring code ?

**Comment by t-bltg** [comment]
How can I access the axis decorations ? I mean the `decorations` dict is filled, but doesn't seem stored somewhere.

**Comment by jkrumbiegel** [comment]
Could be that this dict is just a remnant at this point, do you need it? The LineAxis just needs to communicate its protrusion value outwards, so at least the Axis shouldn't need access. Or is this just for debugging?

**Comment by jkrumbiegel** [comment]
I was mostly using it for debugging as well at the time, must have dropped out of use without me noticing.

**Comment by t-bltg** [comment]
I doesn't seem possible to know the textlabel `boundingbox` beforehand right ?
I think I have to first create the textlabel, and then shift it according to the given rotation ?

**Comment by t-bltg** [comment]
Probably needs rework (how can we trigger viewport update ?), but it seems to work:

rot

**Comment by jkrumbiegel** [comment]
This alignment looks good! Now you have to include the boundingbox width in the protrusion calculation of the lineaxis and take care that this observable actually gets updated whenever rotation changes. You can check how all the other label text related attributes do that, for example the protrusion updates when the string changes, or the font size, etc

**Comment by t-bltg** [comment]
Thanks for the hints !
That wasn't too hard ;)

rot

**Comment by jkrumbiegel** [comment]
Looks great :) now for the final act, check that it still looks good when you flip the xaxis to the top (with an axis title) and when you flip the yaxis to the right. And then reset both rotations to automatic (while flipped) and see that they reset correctly. I think that should cover the behavior well enough.

**Comment by t-bltg** [comment]
This sequence works as expected:
```julia
axis = (
  xlabel = "a nice and long x label for this axis",
  ylabel = "a nice and long y label for this axis",
  yaxisposition = :right,
  xaxisposition = :top,
  xlabelrotation = +π / 4,
  ylabelrotation = 2π / 3,
)
fig, ax, plot = scatter(0:1; axis)

ax.xlabelrotation[] = Makie.automatic
display(fig)

ax.yaxisposition[] = :left
ax.ylabelrotation[] = Makie.automatic
display(fig)

ax.xaxisposition[] = :bottom
ax.xlabelrotation[] = π / 3
display(fig)
```

**Comment by jkrumbiegel** [comment]
Very good! I think you see now what I meant when I said it would be "a bit fiddly" and not just exposing a rotation parameter ;)

**Comment by t-bltg** [comment]
So for the tests, I'd be happy to try to cover a lot of cases, but I didn't quite get how you worked in Makie using reference images and the `Stepper` thing ...

**Comment by jkrumbiegel** [comment]
The stepper is just a simple way to record a few images from the same figure. That's helpful when you want to make sure observable updates happen correctly. So you write one example with a couple of steps. Initial, new rotation, axis flip, back to automatic seems reasonable.

**Comment by t-bltg** [comment]
> The stepper is just a simple way to record a few images from the same figure.

Clever thing, thanks.
So I guess I have to run the tests locally to create the container output and upload it, right ?

**Comment by jkrumbiegel** [comment]
Yes that would make a ton of sense, I've thought about it before but didn't get around to it. If you want to help, you could write down a simple bullet list of things you found difficult when working on this PR, so I have a base to start with. It's difficult for me to imagine in all detail what the process is like for someone new.

**Comment by jkrumbiegel** [comment]
We only have this I think https://github.com/MakieOrg/Makie.jl/blob/master/CONTRIBUTING.md

**Comment by t-bltg** [comment]
> If you want to help

Sure thing, let's do that while it's fresh.

I mean I've laid my hand a few time in `Makie` before, but it was some time ago maybe a year, so we really forget the basics, and the contribution procedure.

It's always tiring to explain the same things again, and I know I always redirect `Plots` contributor for these things buried in the docs ;)

I'll do that in another PR then, should this go in s specific `docs/documentation/...md` file or should I maybe create one ?

**Comment by t-bltg** [comment]
> We only have this I think https://github.com/MakieOrg/Makie.jl/blob/master/CONTRIBUTING.md

Haaa, it's not easily found. I believe it would help (and add more visibility) if this was in a docs section. At least you could search the term `contributing` or `pull requests` or `test suite`, ...

**Comment by jkrumbiegel** [comment]
I think the Contributing.md is fine for now, it's top level and reasonably visible for that reason.

**Comment by t-bltg** [comment]
My bad for not finding `CONTRIBUTING.md` then.
So I guess that this `PR` is ready for review / comments now.

**Comment by jkrumbiegel** [comment]
Sorry I actually didn't reply to this 

>Haaa, it's not easily found. I believe it would help (and add more visibility) if this was in a docs section. At least you could search the term contributing or pull request or test suite, ...

But to the comment before. We could think about copying the `CONTRIBUTING.md` into the docs at each build just as it's done with `NEWS.md` https://github.com/MakieOrg/Makie.jl/blob/master/docs/utils.jl#L14. I think it's standard for these md files to be in the top level, but I agree it would help visibility if they were also in the docs.

**Comment by t-bltg** [comment]
> We could think about copying the CONTRIBUTING.md into the docs at each build just as it's done with NEWS.md

Great idea, that would give immediate visibility in the docs and allow docs search.

**Comment by jkrumbiegel** [comment]
Failing refimages:

Reference
grafik
Recorded
grafik


Reference
grafik
Recorded
grafik

Looks like something's off with the latex string text boundingbox calculation or so?

**Comment by t-bltg** [comment]
Right, let me remove all the un-related changes made in this PR.

**Comment by t-bltg** [comment]
I know, I removed this https://github.com/MakieOrg/Makie.jl/blob/master/src/makielayout/lineaxis.jl#L360-L371, I have to instead add a condition on `labelrotation` being `Automatic` or not.

**Comment by t-bltg** [comment]
Here are the new reference images:

step-1
step-2
step-3
step-4

`pkg> test CairoMakie` passes locally.

**Comment by jkrumbiegel** [comment]
Great, I'll need some time to have a final look over this, but I'll try get around to it soon

**Comment by t-bltg** [comment]
Thanks, as you might observe I've made some small changes un-relevant to this PR, but enhancing clarity or trivial simplifications while developing.

If you don't want them in this PR, tell me so, and I'll remove them.

**Comment by t-bltg** [comment]
I've been thinking about this again, and since we added a default `labelrotation` to the `Colorbar` type, this needs to be tested as well.

I will enhance the tests.

**Comment by t-bltg** [comment]
I think using `Makie.automatic` for the colorbar is more consistent.
I've also enforced type assertions.

Here is the new ref images sequence:

step-1
step-2
step-3
step-4
step-5
step-6
step-7
step-8
step-9

**Comment by t-bltg** [comment]
I think using `Makie.automatic` for the colorbar is more consistent.
I've also enforced type assertions.

Here is the new ref images sequence:

step-1
step-2
step-3
step-4
step-5
step-6
step-7
step-8
step-9

**Comment by t-bltg** [comment]
Hum, the latest commit causes a `WGLMakie` error, which I must admit fail to see by what it is caused:

<details>

```julia
Copied from CI:

Label rotations: Error During Test at /home/runner/work/Makie.jl/Makie.jl/ReferenceTests/src/database.jl:31
  Got exception outside of a @test
  TypeError: Cannot read property 'wgl_camera' of undefined
  Stacktrace:
    [1] error(s::String)
      @ Base ./error.jl:33
    [2] evaljs_value(session::JSServe.Session, js::JSServe.JSCode; error_on_closed::Bool, time_out::Float64)
      @ JSServe ~/.julia/packages/JSServe/kIK9q/src/session.jl:238
    [3] evaljs_value
      @ ~/.julia/packages/JSServe/kIK9q/src/session.jl:207 [inlined]
    [4] insert!(td::WGLMakie.ThreeDisplay, scene::Scene, plot::Poly{Tuple{Vector{HyperRectangle{2, Float32}}}})
      @ WGLMakie ~/work/Makie.jl/Makie.jl/WGLMakie/src/three_plot.jl:24
    [5] insert!
      @ ~/work/Makie.jl/Makie.jl/WGLMakie/src/display.jl:173 [inlined]
    [6] push!(scene::Scene, plot::Poly{Tuple{Vector{HyperRectangle{2, Float32}}}})
      @ Makie ~/work/Makie.jl/Makie.jl/src/scenes.jl:409
    [7] plot!(scene::Scene, P::Type{Poly{Tuple{Vector{HyperRectangle{2, Float32}}}}}, attributes::Attributes, input::Tuple{Observable{Vector{HyperRectangle{2, Float32}}}}, args::Observable{Tuple{Vector{HyperRectangle{2, Float32}}}})
      @ Makie ~/work/Makie.jl/Makie.jl/src/interfaces.jl:422
    [8] plot!(scene::Scene, P::Type{Poly{ArgType} where ArgType}, attributes::Attributes, args::Observable{Vector{HyperRectangle{2, Float32}}}; kw_attributes::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ Makie ~/work/Makie.jl/Makie.jl/src/interfaces.jl:336
    [9] plot!
      @ ~/work/Makie.jl/Makie.jl/src/interfaces.jl:304 [inlined]
   [10] #plot!#165
      @ ~/work/Makie.jl/Makie.jl/src/interfaces.jl:287 [inlined]
   [11] poly!(::Scene, ::Vararg{Any, N} where N; attributes::Base.Iterators.Pairs{Symbol, Any, Tuple{Symbol, Symbol, Symbol}, NamedTuple{(:color, :visible, :inspectable), Tuple{Observable{Vector{RGBA{Float64}}}, Observable{Bool}, Bool}}})
      @ MakieCore ~/work/Makie.jl/Makie.jl/MakieCore/src/recipes.jl:38
   [12] initialize_block!(cb::Colorbar)
      @ Makie ~/work/Makie.jl/Makie.jl/src/makielayout/blocks/colorbar.jl:197
   [13] _block(::Type{Colorbar}, ::Figure; bbox::Nothing, kwargs::Base.Iterators.Pairs{Symbol, Any, Tuple{Symbol, Symbol}, NamedTuple{(:label, :labelrotation), Tuple{String, Int64}}})
      @ Makie ~/work/Makie.jl/Makie.jl/src/makielayout/blocks.jl:408
   [14] _block(::Type{Colorbar}, ::GridPosition; kwargs::Base.Iterators.Pairs{Symbol, Any, Tuple{Symbol, Symbol}, NamedTuple{(:label, :labelrotation), Tuple{String, Int64}}})
      @ Makie ~/work/Makie.jl/Makie.jl/src/makielayout/blocks.jl:294
   [15] #_#1075
      @ ~/work/Makie.jl/Makie.jl/src/makielayout/blocks.jl:279 [inlined]
   [16] macro expansion
      @ ~/work/Makie.jl/Makie.jl/ReferenceTests/src/tests/examples2d.jl:302 [inlined]
   [17] macro expansion
      @ ~/work/Makie.jl/Makie.jl/ReferenceTests/src/database.jl:42 [inlined]
   [18] macro expansion
      @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
   [19] top-level scope
      @ ~/work/Makie.jl/Makie.jl/ReferenceTests/src/database.jl:32
   [20] include(fname::String)
      @ Base.MainInclude ./client.jl:444
   [21] macro expansion
      @ ~/work/Makie.jl/Makie.jl/ReferenceTests/src/tests/refimages.jl:25 [inlined]
   [22] macro expansion
      @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
   [23] top-level scope
      @ ~/work/Makie.jl/Makie.jl/ReferenceTests/src/tests/refimages.jl:25
   [24] include(fname::String)
      @ Base.MainInclude ./client.jl:444
   [25] macro expansion
      @ ~/work/Makie.jl/Makie.jl/ReferenceTests/src/database.jl:95 [inlined]
   [26] macro expansion
      @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
   [27] macro expansion
      @ ~/work/Makie.jl/Makie.jl/ReferenceTests/src/database.jl:94 [inlined]
   [28] macro expansion
      @ ~/work/Makie.jl/Makie.jl/WGLMakie/test/runtests.jl:61 [inlined]
   [29] macro expansion
      @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
   [30] top-level scope
      @ ~/work/Makie.jl/Makie.jl/WGLMakie/test/runtests.jl:59
   [31] include(fname::String)
      @ Base.MainInclude ./client.jl:444
   [32] top-level scope
      @ none:6
   [33] eval
      @ ./boot.jl:360 [inlined]
   [34] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:261
   [35] _start()
      @ Base ./client.jl:485
```

</details>

**Comment by jkrumbiegel** [comment]
No idea about wglmakie, @SimonDanisch ?

The CI doesn't error if there are new images without references, that just triggers bot notifications.

**Comment by t-bltg** [comment]
I've minimized the changes and removed unrelated modifications, but the `WGLMakie` ci error still persists.
The error is related to the `Colorbar` block, but I fail to see the link with the camera.

I am a bit clueless here ...

**Comment by t-bltg** [comment]
I tried to reproduce locally, and a slightly different error, but still occurring when setting the `Colorbar` :

<details>

```julia
ERROR: TypeError: scene is undefined
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] evaljs_value(session::Session, js::JSServe.JSCode; error_on_closed::Bool, time_out::Float64)
    @ JSServe ~/.julia/packages/JSServe/kIK9q/src/session.jl:238
  [3] evaljs_value
    @ ~/.julia/packages/JSServe/kIK9q/src/session.jl:206 [inlined]
  [4] insert!(td::WGLMakie.ThreeDisplay, scene::Scene, plot::Poly{Tuple{Vector{GeometryBasics.HyperRectangle{2, Float32}}}})
    @ WGLMakie ~/.julia/packages/WGLMakie/L5URO/src/three_plot.jl:24
  [5] insert!(td::WGLMakie.Screen, scene::Scene, plot::Poly{Tuple{Vector{GeometryBasics.HyperRectangle{2, Float32}}}})
    @ WGLMakie ~/.julia/packages/WGLMakie/L5URO/src/display.jl:173
  [6] push!(scene::Scene, plot::Poly{Tuple{Vector{GeometryBasics.HyperRectangle{2, Float32}}}})
    @ Makie [...]/Makie.jl/src/scenes.jl:409
  [7] plot!(scene::Scene, P::Type{Poly{Tuple{Vector{GeometryBasics.HyperRectangle{2, Float32}}}}}, attributes::Attributes, input::Tuple{Observable{Vector{GeometryBasics.HyperRectangle{2, Float32}}}}, args::Observable{Tuple{Vector{GeometryBasics.HyperRectangle{2, Float32}}}})
    @ Makie [...]/Makie.jl/src/interfaces.jl:422
  [8] plot!(scene::Scene, P::Type{Poly}, attributes::Attributes, args::Observable{Vector{GeometryBasics.HyperRectangle{2, Float32}}}; kw_attributes::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Makie [...]/Makie.jl/src/interfaces.jl:336
  [9] plot!
    @ [...]/Makie.jl/src/interfaces.jl:303 [inlined]
 [10] #plot!#165
    @ [...]/Makie.jl/src/interfaces.jl:287 [inlined]
 [11] poly!(::Scene, ::Vararg{Any}; attributes::Base.Pairs{Symbol, Any, Tuple{Symbol, Symbol, Symbol}, NamedTuple{(:color, :visible, :inspectable), Tuple{Observable{Vector{ColorTypes.RGBA{Float64}}}, Observable{Bool}, Bool}}})
    @ MakieCore [...]/Makie.jl/MakieCore/src/recipes.jl:38
 [12] initialize_block!(cb::Colorbar)
    @ Makie [...]/Makie.jl/src/makielayout/blocks/colorbar.jl:197
 [13] _block(::Type{Colorbar}, ::Figure; bbox::Nothing, kwargs::Base.Pairs{Symbol, Any, Tuple{Symbol, Symbol}, NamedTuple{(:label, :labelrotation), Tuple{String, Int64}}})
    @ Makie [...]/Makie.jl/src/makielayout/blocks.jl:408
 [14] _block(::Type{Colorbar}, ::GridPosition; kwargs::Base.Pairs{Symbol, Any, Tuple{Symbol, Symbol}, NamedTuple{(:label, :labelrotation), Tuple{String, Int64}}})
    @ Makie [...]/Makie.jl/src/makielayout/blocks.jl:294
 [15] #_#1077
    @ [...]/Makie.jl/src/makielayout/blocks.jl:279 [inlined]
 [16] top-level scope
    @ REPL[21]:1
 [17] eval
    @ ./boot.jl:368 [inlined]
 [18] eval_user_input(ast::Any, backend::REPL.REPLBackend)
    @ REPL ~/share/julia/stdlib/v1.8/REPL/src/REPL.jl:151
 [19] repl_backend_loop(backend::REPL.REPLBackend)
    @ REPL ~/share/julia/stdlib/v1.8/REPL/src/REPL.jl:247
 [20] start_repl_backend(backend::REPL.REPLBackend, consumer::Any)
    @ REPL ~/share/julia/stdlib/v1.8/REPL/src/REPL.jl:232
 [21] run_repl(repl::REPL.AbstractREPL, consumer::Any; backend_on_current_task::Bool)
    @ REPL ~/share/julia/stdlib/v1.8/REPL/src/REPL.jl:369
 [22] run_repl(repl::REPL.AbstractREPL, consumer::Any)
    @ REPL ~/share/julia/stdlib/v1.8/REPL/src/REPL.jl:355
 [23] (::Base.var"#967#969"{Bool, Bool, Bool})(REPL::Module)
    @ Base ./client.jl:419
 [24] #invokelatest#2
    @ ./essentials.jl:729 [inlined]
 [25] invokelatest
    @ ./essentials.jl:726 [inlined]
 [26] run_main_repl(interactive::Bool, quiet::Bool, banner::Bool, history_file::Bool, color_set::Bool)
    @ Base ./client.jl:404
 [27] top-level scope
    @ none:40
```
</details>

**Comment by t-bltg** [comment]
I've tried this PR against https://github.com/MakieOrg/Makie.jl/pull/2428, same error.
The previous example with the colorbar fails in `WGLMakie` on the latest `Makie` release.
I'm going to open a new issue.

**Comment by t-bltg** [comment]
Dropping a note to says that this `PR` is ready, and only needs new reference images merged.

**Review by jkrumbiegel — APPROVED** [review]

**Comment by jkrumbiegel** [comment]
Thank you, @t-bltg!

**Comment by t-bltg** [comment]
Thanks for the help and the constructive comments made on this PR, I couldn't have done without (or would have written sloppy code for sure :)) !

**Pull request merged**
