### PR TITLE
fix silent `LaTeXString` conversion

### PR DESCRIPTION
**Pull request by t-bltg**
# Description

Fix https://github.com/MakieOrg/Makie.jl/issues/2513.

In OP's bug report, the `LaTeXString` was silently converted to a `String`, resulting in `$` signs appearing in the `Axis3D` case.

## Type of change

Delete options that do not apply:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] Added an entry in NEWS.md (for new features and breaking changes)
- [ ] Added or changed relevant sections in the documentation
- [x] Added unit tests for new algorithms, conversion methods, etc.
- [ ] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

**Review by ffreyer — APPROVED** [review]
The test failure is just a communication error so this should be good to go right?

> Error: Resource not accessible by integration

**Comment by t-bltg** [comment]
No, this needs new reference images merged, expanding `Run mshick/add-pr-comment@v1` yields:
```
Run mshick/add-pr-comment@v1
  with:
    message: ## Missing reference images
  Found 1 new images without existing references.
  Upload new reference images before merging this PR.
```

**Comment by asinghvi17** [comment]
I think there are a couple of new reference tests in this round of PRs, Simon mentioned he usually uploads those manually.

**Comment by t-bltg** [comment]
IIUC, this can only be done by contributors with write access (which I don't have).

**Review by jkrumbiegel — APPROVED** [review]

**Pull request merged**
