### PR TITLE
flip

### PR DESCRIPTION
**Pull request by cossio**
# Description

Adds `scale_to=:flip` option for `hist` which flips the direction of the bars.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] Added an entry in CHANGELOG.md (for new features and breaking changes)
- [x] Added or changed relevant sections in the documentation
- [ ] Added unit tests for new algorithms, conversion methods, etc.
- [ ] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

**Comment by ffreyer** [comment]
I noticed `hist` only has one small refimg test for log-scaled axes so I added a more extensive refimg test here:

```julia
data = sin.(1:1000)

fig = Figure(size = (900, 900))
hist(fig[1, 1], data)
hist(fig[1, 2], data, bins = 30, color = :orange)
a, p = hist(fig[1, 3], data, bins = 10, color = :transparent, strokecolor = :red, strokewidth = 4.0)
a.xgridcolor[] = RGBAf(0,0,0,1); a.ygridcolor[] = RGBAf(0,0,0,1)

hist(fig[2, 1], data, normalization = :pdf)
hist(fig[2, 2], data, normalization = :density, color = 1:15)
hist(fig[2, 3], data, normalization = :probability)

hist(fig[3, 1], data, offset = 20.0)
hlines!(0.0, color = :black, linewidth = 3)
hist(fig[3, 2], data, fillto = -20.0)
hlines!(0.0, color = :black, linewidth = 3)
hist(fig[3, 3], data, bar_labels = :y, label_size = 10, bins = 10)

hist(fig[4, 1], data, scale_to = 1.0, direction = :x)
hist(fig[4, 2], data, scale_to = :flip, bins = 10,
    bar_labels = :x, label_size = 12, label_color = RGBf(1,1,0.5), label_offset = -20
)
hist(fig[4, 3], data, weights = 1.0 ./ (2.0 .+ data))

fig
```

Screenshot from 2024-03-27 16-17-51

**Comment by jkrumbiegel** [comment]
Is there one where offset and scale to or flip interact?

**Comment by ffreyer** [comment]
> Is there one where offset and scale to or flip interact?

I updated the refimg to do that some more. Now there is a :flip + offset and some other combinations. I also updated barplot a bit so you can have `label_offset::Vector` and `offset` is considered in the placement of labels. 

I am not sure how `offset` and I guess also `fillto` should interact with `scale_to = :flip/negative`. Should they get flipped as well? Currently they follow plot x/y directions.

```julia
data = sin.(1:1000)

fig = Figure(size = (900, 900))
hist(fig[1, 1], data)
hist(fig[1, 2], data, bins = 30, color = :orange)
a, p = hist(fig[1, 3], data, bins = 10, color = :transparent, strokecolor = :red, strokewidth = 4.0)
a.xgridcolor[] = RGBAf(0,0,0,1); a.ygridcolor[] = RGBAf(0,0,0,1)

hist(fig[2, 1], data, normalization = :pdf, direction = :x)
hist(fig[2, 2], data, normalization = :density, color = 1:15)
hist(fig[2, 3], data, normalization = :probability, scale_to = :flip)

hist(fig[3, 1], data, offset = 20.0)
hlines!(0.0, color = :black, linewidth = 3)
hist(fig[3, 2], data, fillto = 1.0, scale_to = -5.0, direction = :x)
vlines!(0.0, color = :black, linewidth = 3)
hist(fig[3, 3], data, bar_labels = :y, label_size = 10, bins = 10)

hist(
    fig[4, 1], data, scale_to = :flip, offset = 20,
    bar_labels = :x, label_size = 12, label_color = :green
)
hlines!(0.0, color = :black, linewidth = 3)
i12 = mod1.(1:10, 2)
hist(fig[4, 2], data, scale_to = :flip, bins = 10, direction = :x,
    bar_labels = :x, label_size = [14, 10][i12],
    label_color = [:yellow, :blue][i12], label_offset = [-30, 10][i12]
)
hist(fig[4, 3], data, weights = 1.0 ./ (2.0 .+ data))

fig
```

Screenshot from 2024-03-27 17-01-18

**Comment by jkrumbiegel** [comment]
> I am not sure how offset and I guess also fillto should interact with scale_to = :flip/negative

I would say offset just translates the whole histogram somewhere, independent of scale. And then fillto would be relative to that zero-line that offset sets I guess, otherwise it doesn't really make sense.

**Review by ffreyer — APPROVED** [review]

**Pull request merged**
