### PR TITLE
Introduce heatmap shader

### PR DESCRIPTION
**Pull request by SimonDanisch**
Which resamples a large image on zoom etc.
I first wanted to add it to `datashader(matrix)`, but realized we need really different attributes, so now it's `heatmapshader(matrix)`.
I also thought about adding it to heatmap directly, but that seemed to complicated, since then it would need to be implemented in the backends due to it being an atomic plot, without having a type to dispatch on.
This allows to plot really large heatmaps speedily, and may even work for out of RAM data (not tested, would need e.g. diskarrays as input).

### Changes in this PR:

* Resampling Updating scheme for as little data transfer as possible
* Implement interpolation based resampling scheme
* Implement a simple Gaussian Pyramid for higher quality resampling
* Documentation & tests

###  Since this was heavily tested with WGLMakie under non optimal connections, this PR includes a few more fixes:

* Debug why scroll is still really slow (It was DataInspector registering a very expensive event on scroll)
* Debugging why async/throttled data inspector is still slowing down scrolling (Bonito needs its own channel and message processing [#215](https://github.com/SimonDanisch/Bonito.jl/pull/215), to not hang on async data inspector calls (which call Bonito.evaljs_value, which sends a message to the browser and needs to wait on a reply))

### CODE REVIEW

**Comment by jkrumbiegel** [comment]
Would it be better if it didn't have heatmap in its name then? I wonder how confusing it would be to have a fast and slow heatmap primitive

**Comment by SimonDanisch** [comment]
Hm isnt that just hiding the obvious? I mean the fact that we have then another way of plotting a heatmap won't go away with another name, will it?
Maybe we could also do:
`heatmap(Resample(data))` or something like that...

**Comment by jkrumbiegel** [comment]
Yeah ideal would be if this could be a part of heatmap, I agree.

**Comment by SimonDanisch** [comment]
They don't, they differ from datashader ;)

**Comment by asinghvi17** [comment]
The only unique attribute looks like `max_resolution = 1024`, so could that just be a kwarg to `Resample` instead of heatmap?

**Pull request merged**
