### PR TITLE
Actually use `linestyle` in `triplot`

### PR DESCRIPTION
**Pull request by DanielVandH**
# Description

Noticed that `triplot` wasn't using the `linestyle` argument

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] Added an entry in CHANGELOG.md (for new features and breaking changes)
- [x] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

**Comment by ffreyer** [comment]
I tweaked another refimg instead of adding a new one to save a bit of CI time.

I also noticed that some lines are overlapping. I guess that's expected though?

**Comment by DanielVandH** [comment]
> I also noticed that some lines are overlapping. I guess that's expected though?

Is there a way to view the new images from the CI without going into the code itself? I can double check.

**Comment by ffreyer** [comment]
It's easier to see when you make the plot locally an rescale the window. I think all the central lines are duplicated. In this example the one to the top left appears solid, along with some others:

image

In your example the one straight down in the center and two diagonal ones connected to either endpoint of that line show it.

**Comment by ffreyer** [comment]
Actually maybe that's just poly?

**Comment by ffreyer** [comment]
Yea nvm, that's just #2694. I'll merge this once ci passes

**Pull request merged**
