### PR TITLE
Fix setting a monitor specified via GLFW

### LINKED ISSUE #2640: GLMakie: Specifying monitor not functional
The current implementation of specifying the monitor in GLMakie seems to be broken.
This script is enough to get a stacktrace:
```julia
using GLMakie

config = Makie.CURRENT_DEFAULT_THEME[:GLMakie]
config[:monitor][] = GLMakie.GLFW.GetPrimaryMonitor()

GLMakie.activate!(; config...)

f = Figure()
```
```julia
ERROR: MethodError: no method matching SetWindowMonitor(::GLFW.Window, ::GLFW.Monitor)
Closest candidates are:
  SetWindowMonitor(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any) at C:\Users\storm\.julia\packages\GLFW\BWxfF\src\glfw3.jl:609
Stacktrace:
  [1] apply_config!(screen::GLMakie.Screen{GLFW.Window}, config::GLMakie.ScreenConfig; visible::Bool, start_renderloop::Bool)
    @ GLMakie C:\Users\storm\.julia\packages\GLMakie\6Blp9\src\screen.jl:317
  [2] GLMakie.Screen(scene::Scene, config::GLMakie.ScreenConfig; visible::Bool, start_renderloop::Bool)    
    @ GLMakie C:\Users\storm\.julia\packages\GLMakie\6Blp9\src\screen.jl:384
  [3] GLMakie.Screen(scene::Scene, config::GLMakie.ScreenConfig)
    @ GLMakie C:\Users\storm\.julia\packages\GLMakie\6Blp9\src\screen.jl:382
  [4] getscreen(::Module, ::Scene; screen_config::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Makie C:\Users\storm\.julia\packages\Makie\Za3LL\src\display.jl:335
  [5] getscreen
    @ C:\Users\storm\.julia\packages\Makie\Za3LL\src\display.jl:323 [inlined]
  [6] display(figlike::Figure; backend::Module, update::Bool, screen_config::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Makie C:\Users\storm\.julia\packages\Makie\Za3LL\src\display.jl:147
  [7] display(figlike::Figure)
    @ Makie C:\Users\storm\.julia\packages\Makie\Za3LL\src\display.jl:132
  [8] #invokelatest#2
    @ .\essentials.jl:729 [inlined]
  [9] invokelatest
    @ .\essentials.jl:726 [inlined]
 [10] (::VSCodeServer.var"#66#70"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})()
    @ VSCodeServer c:\Users\storm\.vscode\extensions\julialang.language-julia-1.38.2\scripts\packages\VSCodeServer\src\eval.jl:199
 [11] withpath(f::VSCodeServer.var"#66#70"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams}, path::String)
    @ VSCodeServer c:\Users\storm\.vscode\extensions\julialang.language-julia-1.38.2\scripts\packages\VSCodeServer\src\repl.jl:249
 [12] (::VSCodeServer.var"#65#69"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})()
    @ VSCodeServer c:\Users\storm\.vscode\extensions\julialang.language-julia-1.38.2\scripts\packages\VSCodeServer\src\eval.jl:155
 [13] hideprompt(f::VSCodeServer.var"#65#69"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})
    @ VSCodeServer c:\Users\storm\.vscode\extensions\julialang.language-julia-1.38.2\scripts\packages\VSCodeServer\src\repl.jl:38
 [14] (::VSCodeServer.var"#64#68"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})()
    @ VSCodeServer c:\Users\storm\.vscode\extensions\julialang.language-julia-1.38.2\scripts\packages\VSCodeServer\src\eval.jl:126
 [15] with_logstate(f::Function, logstate::Any)
    @ Base.CoreLogging .\logging.jl:511
 [16] with_logger
    @ .\logging.jl:623 [inlined]
 [17] (::VSCodeServer.var"#63#67"{VSCodeServer.ReplRunCodeRequestParams})()
    @ VSCodeServer c:\Users\storm\.vscode\extensions\julialang.language-julia-1.38.2\scripts\packages\VSCodeServer\src\eval.jl:225
 [18] #invokelatest#2
    @ .\essentials.jl:729 [inlined]
 [19] invokelatest(::Any)
    @ Base .\essentials.jl:726
 [20] macro expansion
    @ c:\Users\storm\.vscode\extensions\julialang.language-julia-1.38.2\scripts\packages\VSCodeServer\src\eval.jl:34 [inlined]
 [21] (::VSCodeServer.var"#61#62")()
    @ VSCodeServer .\task.jl:484
```
The code responsible seems to be:
https://github.com/MakieOrg/Makie.jl/blob/156e651ffd1b20eed3f511f925c1e8ac4eed1474/GLMakie/src/screen.jl#L319-L321
The correct function call seems to need 7 args:
`SetWindowMonitor(window, monitor, xpos, ypos, width, height, refreshRate)`
https://www.glfw.org/docs/3.3/group__window.html#ga81c76c418af80a1cce7055bccb0ae0a7

### PR DESCRIPTION
**Pull request by mkoculak**
# Description

Fixes #2640 

This PR aims to fix spawning a new figure in a manually specified monitor via GLFW.
Currently, setting a monitor in config results in error, where `SetWindowMonitor()` is called without enough number of parameters.

Here I get the missing values from `MonitorProperties()` and call the above mentioned function properly.
However, adding an `@info` check on the parameters reveals that the whole `apply_config!()` function is called in this process twice and the second time the properties are overwritten by defaults somewhere else in the codebase.

A quick fix is to always make a `Figure()` or similar call with `resolution` stated explicitly (as in the example below).
Yet, in GLFW `SetWindowMonitor()` is a function to create a full-screen window (in this case borderless), so maybe applying default values is not ideal in any case (since with the default (800,600) the rest of the screen is just black. But I don't know how to mitigate it.

The MWE to check the working solution:
```julia
using GLMakie
GLMakie.activate!(; monitor = GLMakie.GLFW.GetPrimaryMonitor())
f = Figure(resolution=(2560,1440))
s = display(f)
# This is the only way I found to close the window
GLMakie.destroy!(s)
```

Any suggestions for improvements are definitely welcomed!

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] Added an entry in NEWS.md (for new features and breaking changes)
- [ ] Added or changed relevant sections in the documentation
- [ ] Added unit tests for new algorithms, conversion methods, etc.
- [ ] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

**Comment by asinghvi17** [comment]
From the [GLFW docs](https://www.glfw.org/docs/3.3/group__window.html#ga81c76c418af80a1cce7055bccb0ae0a7:~:text=This%20function%20sets%20the%20monitor,%2C%20makes%20it%20windowed%20mode.), 

> This function sets the monitor that the window uses for full screen mode or, if the monitor is NULL, makes it windowed mode.

so I don't think that `GLFW.SetWindowMonitor` is the right function to use here, although I'm not sure what is.

**Comment by mkoculak** [comment]
Yeah, I agree it does not seem optimal, but on the other hand, there is no clear alternative for opening a new non-fullscreen window on a selected monitor. From the said docs, it would suggest that one should use `SetWindowMonitor` to make adjustments to already created window:
> Once you have created the window, you can switch it between windowed and full screen mode with [glfwSetWindowMonitor](https://www.glfw.org/docs/3.3/group__window.html#ga81c76c418af80a1cce7055bccb0ae0a7). This will not affect its OpenGL or OpenGL ES context.
>By default, newly created windows use the placement recommended by the window system. To create the window at a specific position, make it initially invisible using the [GLFW_VISIBLE](https://www.glfw.org/docs/3.3/window_guide.html#GLFW_VISIBLE_hint) window hint, set its [position](https://www.glfw.org/docs/3.3/window_guide.html#window_pos) and then [show](https://www.glfw.org/docs/3.3/window_guide.html#window_hide) it.

So it seems the best way would be to pass the monitor pointer during window creation, but I am not sure if it is possible within `activate!` call. Nevertheless, making two calls to `SetWindowMonitor`, with and without monitor pointer, would allow to move and resize any window, even those, that are already open (which would still be neat, I think).

**Comment by SimonDanisch** [comment]
Hm it does look to me like glfw indeed doesn't allow to just move a window to a specific monitor: https://www.glfw.org/docs/latest/window_guide.html#window_monitor
I guess this is part of the os settings, which GLFW can't control?

**Comment by SimonDanisch** [comment]
I will close this for now, since I'm not sure how to make this work correctly.

**Pull request closed without merging**
