### PR TITLE
fix legend colorrange

### PR DESCRIPTION
**Pull request by t-bltg**
# Description

Fix https://github.com/MakieOrg/Makie.jl/issues/3532.

## Type of change

Delete options that do not apply:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] Added an entry in NEWS.md (for new features and breaking changes)
- [ ] Added or changed relevant sections in the documentation
- [ ] Added unit tests for new algorithms, conversion methods, etc.
- [x] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

**Comment by t-bltg** [comment]
New reference images:

leg1
leg2

**Comment by jkrumbiegel** [comment]
This doesn't copy the colormap I think, so it would break if your test didn't use the default. Could you add the same treatment (and tests) for marker and poly elements as well? Then everything would work the same way.

**Comment by t-bltg** [comment]
> This doesn't copy the colormap I think, so it would break if your test didn't use the default.

Good point, I will check that.

> Could you add the same treatment (and tests) for marker and poly elements as well?

Will do.

**Comment by t-bltg** [comment]
@jkrumbiegel , I've update the examples in https://github.com/MakieOrg/Makie.jl/pull/3536#issuecomment-1880028133, added reference tests, and fixed propagation of the `colormap` attribute.

Does that fix your requests ?

**Comment by jkrumbiegel** [comment]
Thanks again for the PR, I've pushed another PR that does a slightly different approach over here https://github.com/MakieOrg/Makie.jl/pull/3587 but this helped me get that one done

**Pull request closed without merging**
