### PR TITLE
Scatterjitter

### PR DESCRIPTION
**Pull request by behinger**
# Description

Fixes https://github.com/MakieOrg/AlgebraOfGraphics.jl/issues/253

Adds weighted-jitter along the density of the distribution

## Type of change
image

Delete options that do not apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] Added an entry in NEWS.md (for new features and breaking changes)
- [x] Added or changed relevant sections in the documentation
- [ ] Added unit tests for new algorithms, conversion methods, etc.
- [ ] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

**Comment by ffreyer** [comment]
I think it would be better to have this as function you can apply to your data rather than a new plot type. E.g. `scatter(jitter(xs), ys)`. That could then be reused with lines and other plotting primitives without the need for extra recipes.

**Comment by behinger** [comment]
could such a function work with AoG?

PS: I made something related with Dodge, e.g. `Dodge(Scatter,...)` - but the other way round ;)
https://github.com/MakieOrg/AlgebraOfGraphics.jl/issues/393#issuecomment-1417789588

**Comment by behinger** [comment]
further, jitter would need access to both `x` & `y`, x to jitter, y to calculate the kde

**Comment by ffreyer** [comment]
`jitter(xs, ys)` and/or `jitter(ps)` would be fine too

**Comment by behinger** [comment]
It is still unclear to me how this would work with AoG.jl

**Comment by behinger** [comment]
ok- then I would have to rewrite it though, to follow the AoG syntax. This is unlikely to happen in the next months, pretty swamped.

Here is an example:
https://github.com/MakieOrg/AlgebraOfGraphics.jl/blob/master/src/transformations/smooth.jl

I could also move the whole recipe to AoG

**Comment by asinghvi17** [comment]
This is implemented in https://github.com/asinghvi17/SwarmMakie.jl as an extra algorithm for beeswarm plots :)

**Pull request closed without merging**
