### PR TITLE
Exception Handling for `current_axis()` in `figureplotting.jl`

### LINKED ISSUE #2903: Better error message for plot!() when no current axis exists
Currently:

```julia
julia> using Makie, CairoMakie, GeoMakie
[ Info: Precompiling GeoMakie [db073c08-6b98-4ee5-b6a4-5efafb3259c6]

julia> image!(rand(10, 19))
ERROR: MethodError: no method matching current_axis(::Nothing)

Closest candidates are:
  current_axis()
   @ Makie ~/Documents/Business/India/XKDR/dev/testing/Makie.jl/src/figures.jl:37
  current_axis(::Figure)
   @ Makie ~/Documents/Business/India/XKDR/dev/testing/Makie.jl/src/figures.jl:38

Stacktrace:
 [1] plot!(P::Type{Image}, args::Matrix{Float64}; kw_attributes::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Makie ~/Documents/Business/India/XKDR/dev/testing/Makie.jl/src/figureplotting.jl:65
 [2] plot!
   @ ~/Documents/Business/India/XKDR/dev/testing/Makie.jl/src/figureplotting.jl:64 [inlined]
 [3] #image!#16
   @ ~/Documents/Business/India/XKDR/dev/testing/Makie.jl/MakieCore/src/recipes.jl:38 [inlined]
 [4] image!(args::Matrix{Float64})
   @ MakieCore ~/Documents/Business/India/XKDR/dev/testing/Makie.jl/MakieCore/src/recipes.jl:37
 [5] top-level scope
   @ REPL[5]:1
```

perhaps a try-catch statement in that last `plot!` statement could help?

### PR DESCRIPTION
**Pull request by vortex73**
# Description

Fixes #2903

Added a try/catch block to `figureplotting.jl` to check whether `current_figure()` returns `nothing`

## Type of change

Delete options that do not apply:

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by jkrumbiegel** [comment]
Hi, thanks for the PR! You don't need try/catch here, you can first assign the result of `current_figure()` to a variable and check if thats `=== nothing`, and error in that case. try catch would catch all other possible errors as well, so that's usually not what you want

**Comment by vortex73** [comment]
Have made corrections. Please check .

**Comment by jkrumbiegel** [comment]
I would mirror the line below: `isnothing(ax) && error("There is no current axis to plot into.")` and just write the same for figure (the users won't know what functions are called internally with what arguments)

**Comment by vortex73** [comment]
I have made the changes as per my understanding please let me know if anything went wrong. Also just for my understanding, why was the conditional approach incorrect?

**Comment by jkrumbiegel** [comment]
It was not incorrect, it is just simpler to understand if similar code is handled in a similar way, and the axis statement already existed right below.

**Comment by vortex73** [comment]
No other changes needed right?

**Review by asinghvi17 — APPROVED** [review]
Looks good to me, thanks @vortex73!

**Comment by vortex73** [comment]
@jkrumbiegel if all's okay could you please approve the merge so i can make changes to my forked branch.

**Pull request merged**
