### PR TITLE
Add `strokestyle` attribute to `Box`

### PR DESCRIPTION
**Pull request by nHackel**
Hello! I've recently used the `Box` with cornerradius to create a plot and wanted to adapt the stroke style and found no option to do that.

# Description
This PR adds the `strokestyle` keyword to a `Box`:
box

For the implementation I also had to adapt a check for compatible linestyles in `CairoMakie`, which was incompatible with the return type of `convert_attribute` for `key"linestyle`.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] Added an entry in NEWS.md (for new features and breaking changes)
- [ ] Added or changed relevant sections in the documentation
- [x] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

**Comment by jkrumbiegel** [comment]
Hi, thanks for the PR! I think we call that property `linestyle` everywhere, even if other properties have `stroke-` as a prefix. But might as well keep in line with that convention for now

**Comment by nHackel** [comment]
Ah, okay! I'm essentially building my first more involved Makie figure and haven't used many keywords so far. 

In `src/makielayout/types.jl` I saw a few types with `x-` prefix but they also seem to have multiple linestyles per type. I can adapt it to linestyle.

Do you think image reference tests are necessary and if so could you point me in the right direction? I was mainly following your rounded corner PR and haven't strayed too far from files you changed there, so a bit unsure of the testing is setup

**Comment by jkrumbiegel** [comment]
Yeah reference images are good practice, it's hard to unit-test visual attributes. You could add a test for `Box` here https://github.com/MakieOrg/Makie.jl/blob/master/ReferenceTests/src/tests/figures_and_makielayout.jl, just a `Figure` with a couple boxes, each of which exercises some of the functionality. And it's good to make the differences salient, like using thick strokes, big rounded corners, etc, so that visual changes are picked up well.

**Review by SimonDanisch — APPROVED** [review]

**Review by jkrumbiegel — APPROVED** [review]
Thanks, looks good!

**Pull request merged**
