### PR TITLE
Interpolate Makie in the `@Block` macro

### PR DESCRIPTION
**Pull request by asinghvi17**
Allows `@Block` to work in any scenario regardless of whether Makie was imported or not (eg if someone only imported CairoMakie).  With this, defining a `@Block` in an external package works well.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by jkrumbiegel** [comment]
This doesn't look correct to me, should work without interpolation. It's probably better to check the escaping logic, maybe too much is escaped that doesn't need to be. Not sure

**Comment by asinghvi17** [comment]
Should the statement be run in the Makie module or the user's module?  The latter is probably better for stacktraces, but the former lends a bit more convenience.

**Comment by jkrumbiegel** [comment]
wherever the macro is called, but its symbols should be default refer to the Makie module if they are not escaped, which they shouldn't be I guess

**Comment by asinghvi17** [comment]
Well if we escape it then the stacktrace points to where the user wrote `@Block`, and if we don't then it points to Makie's definition of `@Block` instead.

The only scenario in which this wouldn't work is if someone loads only a backend package (GLMakie, etc) and not Makie.  Since we recommend this in the docs, I think it makes sense to interpolate Makie just in case.

**Comment by SimonDanisch** [comment]
Is this still needed after https://github.com/MakieOrg/Makie.jl/pull/2645?

**Comment by asinghvi17** [comment]
Will check and get back to you!

**Comment by SimonDanisch** [comment]
I think most should be fixed in #2645

**Pull request closed without merging**
