### PR TITLE
Fix DataInspector using invalid attribute strokewidth for plot type Wireframe

### LINKED ISSUE #3912: Invalid attribute strokewidth for plot type Wireframe, Makie v0.21.2
- [x] are you running newest version (version from docs) ?
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on?

GLMakie v0.10.2, Makie v0.21.2
Windows 10, Intel i7-1370P integrated graphics

Same example as in https://github.com/MakieOrg/Makie.jl/issues/1951
```
using GLMakie
fig = Figure()
ax = Axis(fig[1,1])
barplot!(ax, 50*rand(100), direction = :x)
DataInspector(fig)
```
when hovering mouse on bars, gives
```
julia> Error in callback:
Invalid attribute strokewidth for plot type Wireframe.

The available plot attributes for Wireframe are:

alpha     colorrange  depth_shift  inspectable      inspector_label  linewidth  nan_color  ssao            visible
color     colorscale  fxaa         inspector_clear  linecap          lowclip    overdraw   transformation
colormap  cycle       highclip     inspector_hover  linestyle        model      space      transparency


Generic attributes are:

cycle  dim_conversions  label  model  rasterize  transformation  xautolimits  yautolimits  zautolimits


Stacktrace:
  [1] validate_attribute_keys(P::Type{Wireframe}, kw::Dict{Symbol, Any})
    @ MakieCore C:\Users\jaakkor2\.julia\packages\MakieCore\8S3xT\src\recipes.jl:732
  [2] Wireframe{Tuple{GeometryBasics.HyperRectangle{2, Float64}}}(kw::Dict{Symbol, Any}, args::Vector{Any}, converted::Vector{Observable}, deregister_callbacks::Vector{Observables.ObserverFunction})
    @ MakieCore C:\Users\jaakkor2\.julia\packages\MakieCore\8S3xT\src\types.jl:86
  [3] (Wireframe)(user_args::Tuple{GeometryBasics.HyperRectangle{2, Float64}}, user_attributes::Dict{Symbol, Any})
    @ Makie C:\Users\jaakkor2\.julia\packages\Makie\We6MY\src\interfaces.jl:276
  [4] _create_plot!(F::Function, attributes::Dict{Symbol, Any}, scene::Scene, args::GeometryBasics.HyperRectangle{2, Float64})
    @ Makie C:\Users\jaakkor2\.julia\packages\Makie\We6MY\src\figureplotting.jl:390
  [5] wireframe!(::Scene, ::Vararg{Any}; kw::@Kwargs{model::StaticArraysCore.SMatrix{4, 4, Float64, 16}, color::Observable{Any}, strokewidth::Observable{Any}, linestyle::Observable{Any}, visible::Observable{Any}, inspectable::Bool})
    @ MakieCore C:\Users\jaakkor2\.julia\packages\MakieCore\8S3xT\src\recipes.jl:440
  [6] show_data(inspector::DataInspector, plot::Plot{Makie.barplot, Tuple{Vector{Point{2, Float64}}}}, idx::Int64)
    @ Makie C:\Users\jaakkor2\.julia\packages\Makie\We6MY\src\interaction\inspector.jl:825
  [7] show_data
    @ C:\Users\jaakkor2\.julia\packages\Makie\We6MY\src\interaction\inspector.jl:805 [inlined]
  [8] show_data_recursion(inspector::DataInspector, plot::Plot{Makie.barplot, Tuple{Vector{Point{2, Float64}}}}, idx::UInt32, source::Mesh{Tuple{GeometryBasics.Mesh{2, Float64, GeometryBasics.Ngon{2, Float64, 3, Point{2, Float64}}, GeometryBasics.SimpleFaceView{2, Float64, 3, GeometryBasics.OffsetInteger{-1, UInt32}, Point{2, Float64}, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}}}})
    @ Makie C:\Users\jaakkor2\.julia\packages\Makie\We6MY\src\interaction\inspector.jl:359
  [9] show_data_recursion(inspector::DataInspector, plot::Poly{Tuple{Vector{GeometryBasics.HyperRectangle{2, Float64}}}}, idx::UInt32, source::Mesh{Tuple{GeometryBasics.Mesh{2, Float64, GeometryBasics.Ngon{2, Float64, 3, Point{2, Float64}}, GeometryBasics.SimpleFaceView{2, Float64, 3, GeometryBasics.OffsetInteger{-1, UInt32}, Point{2, Float64}, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}}}})
    @ Makie C:\Users\jaakkor2\.julia\packages\Makie\We6MY\src\interaction\inspector.jl:351
 [10] show_data_recursion(inspector::DataInspector, plot::Mesh{Tuple{Vector{GeometryBasics.Mesh{2, Float64, GeometryBasics.Ngon{2, Float64, 3, Point{2, Float64}}, GeometryBasics.SimpleFaceView{2, Float64, 3, GeometryBasics.OffsetInteger{-1, UInt32}, Point{2, Float64}, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}}}}}, idx::UInt32, source::Mesh{Tuple{GeometryBasics.Mesh{2, Float64, GeometryBasics.Ngon{2, Float64, 3, Point{2, Float64}}, GeometryBasics.SimpleFaceView{2, Float64, 3, GeometryBasics.OffsetInteger{-1, UInt32}, Point{2, Float64}, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}}}})
    @ Makie C:\Users\jaakkor2\.julia\packages\Makie\We6MY\src\interaction\inspector.jl:351
 [11] show_data_recursion(inspector::DataInspector, plot::Mesh{Tuple{GeometryBasics.Mesh{2, Float64, GeometryBasics.Ngon{2, Float64, 3, Point{2, Float64}}, GeometryBasics.SimpleFaceView{2, Float64, 3, GeometryBasics.OffsetInteger{-1, UInt32}, Point{2, Float64}, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}}}}, idx::UInt32)
    @ Makie C:\Users\jaakkor2\.julia\packages\Makie\We6MY\src\interaction\inspector.jl:329
 [12] on_hover(inspector::DataInspector)
    @ Makie C:\Users\jaakkor2\.julia\packages\Makie\We6MY\src\interaction\inspector.jl:307
 [13] (::Makie.var"#1312#1316"{DataInspector})(::Tuple{Float64, Float64})
    @ Makie C:\Users\jaakkor2\.julia\packages\Makie\We6MY\src\interaction\inspector.jl:280
 [14] #invokelatest#2
    @ .\essentials.jl:892 [inlined]
 [15] invokelatest
    @ .\essentials.jl:889 [inlined]
 [16] notify
    @ C:\Users\jaakkor2\.julia\packages\Observables\YdEbO\src\Observables.jl:206 [inlined]
 [17] setindex!
    @ C:\Users\jaakkor2\.julia\packages\Observables\YdEbO\src\Observables.jl:123 [inlined]
 [18] (::GLMakie.MousePositionUpdater)(::Nothing)
    @ GLMakie C:\Users\jaakkor2\.julia\packages\GLMakie\Wvj4h\src\events.jl:6
 [19] #invokelatest#2
    @ .\essentials.jl:892 [inlined]
 [20] invokelatest
    @ .\essentials.jl:889 [inlined]
 [21] notify
    @ C:\Users\jaakkor2\.julia\packages\Observables\YdEbO\src\Observables.jl:206 [inlined]
 [22] pollevents(screen::GLMakie.Screen{GLFW.Window})
    @ GLMakie C:\Users\jaakkor2\.julia\packages\GLMakie\Wvj4h\src\screen.jl:450
 [23] on_demand_renderloop(screen::GLMakie.Screen{GLFW.Window})
    @ GLMakie C:\Users\jaakkor2\.julia\packages\GLMakie\Wvj4h\src\screen.jl:937
 [24] renderloop(screen::GLMakie.Screen{GLFW.Window})
    @ GLMakie C:\Users\jaakkor2\.julia\packages\GLMakie\Wvj4h\src\screen.jl:963
 [25] (::GLMakie.var"#67#68"{GLMakie.Screen{GLFW.Window}})()
    @ GLMakie C:\Users\jaakkor2\.julia\packages\GLMakie\Wvj4h\src\screen.jl:824
```

### PR DESCRIPTION
**Pull request by jaakkor2**
# Description

Fixes #3912

`wireframe!` used attribute `strokewidth` that should have been `linewidth`

## Type of change

Delete options that do not apply:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] Added an entry in CHANGELOG.md (for new features and breaking changes)
- [ ] Added or changed relevant sections in the documentation
- [ ] Added unit tests for new algorithms, conversion methods, etc.
- [ ] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

**Comment by jaakkor2** [comment]
`lines!` does not have `strokewidth` attribute either
https://github.com/MakieOrg/Makie.jl/blob/v0.21.3/src/interaction/inspector.jl#L925
https://github.com/MakieOrg/Makie.jl/blob/v0.21.3/src/interaction/inspector.jl#L1008

**Comment by jaakkor2** [comment]
Gentle ping @SimonDanisch

**Comment by SimonDanisch** [comment]
Sorry we can't just merge breaking changes like this... Maybe we can make it non breaking for now? There's some machinery for that in recipes.jl

**Comment by jaakkor2** [comment]
Uh, I am lost, neither in v0.20 nor v0.21 `strokewidth` was an attribute for `wireframe`, but on v0.21 error is shown for invalid attributes. This is a bugfix for `DataInspector`.

**Comment by ffreyer** [comment]
Oh, this is just about a call to wireframe. I thought it was about renaming an attribute in the recipe, which would be breaking. This should be fine to merge after adding an entry to https://github.com/MakieOrg/Makie.jl/blob/master/CHANGELOG.md

**Comment by SimonDanisch** [comment]
Thanks! :) 
CI is failing because of https://github.com/MakieOrg/Makie.jl/pull/4003

**Pull request merged**
