### PR TITLE
move poly to MakieCore

### PR DESCRIPTION
**Pull request by jw3126**
https://github.com/JuliaGeo/GeoInterface.jl/pull/71#discussion_r994977229

### CODE REVIEW

**Comment by jw3126** [comment]
Bump! Is there some arguments against this? Would be really helpful for us to have lightweight access to poly.

**Comment by SimonDanisch** [comment]
Yes, thank you, I think this is a good idea, although it's not really clear on where to draw the line... But lets just merge this for now, if it helps your use case! :)

**Comment by jw3126** [comment]
@SimonDanisch thanks for merging! What are the downsides of declaring more polytypes in MakieCore?

**Comment by jkrumbiegel** [comment]
it's just that makiecore is supposed to be lightweight, and the more we add the less it is that

**Comment by SimonDanisch** [comment]
Also we really want to start having a "real" solution, where you can just address any plot/recipe without taking on the dependency ;)

**Comment by jw3126** [comment]
> Also we really want to start having a "real" solution, where you can just address any plot/recipe without taking on the dependency ;)

Sounds awesome!

**Comment by jw3126** [comment]
> it's just that makiecore is supposed to be lightweight, and the more we add the less it is that

But do `@recipe` calls make the package more heavy weight? I am not talking about moving any implementations to MakieCore. Just adding more `"some docs" @recipe(...)` to MakieCore.

**Comment by SimonDanisch** [comment]
I don't really think it matters in this case, and won't for a couple more, as long as we don't need further package dependencies. It'll just a bit random, which recipes make it into the exclusive MakieCore club ;)

**Comment by jw3126** [comment]
Can we have a MakieCore release? Should I bump the version?

**Pull request merged**
