### PR TITLE
Don't mesh a polygon in CairoMakie

### PR DESCRIPTION
**Pull request by jaakkor2**
# CairoMakie plot of a polygon is a mesh resulting in a raster .svg file

Fixes https://github.com/MakieOrg/Makie.jl/issues/2396

Treat a polygon same way as an array of polygons

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] Added unit tests for new algorithms, conversion methods, etc.

### CODE REVIEW

**Comment by jkrumbiegel** [comment]
Would be great if you could add a plot with a couple different `poly` versions (including your new one) to this file to ensure they don't get rasterized again in the future.

https://github.com/MakieOrg/Makie.jl/blob/master/CairoMakie/test/rasterization_tests.jl

**Comment by jaakkor2** [comment]
Thank you @jkrumbiegel for pointing out the location of the rasterization tests.  I now simply added a simplest polygon to the existing testset.

**Comment by fatteneder** [comment]
This PR broke the 'polygon with hole' example #2456

**Comment by jkrumbiegel** [comment]
Ah damn it seemed not to have a visual regression test. It shouldn't be too hard to fix, sometimes holes don't work right if the interiors are not the opposite winding order, which they should have but don't always have. Not sure what the problem was exactly in the docs case.

**Pull request merged**
