### PR TITLE
Tex theme

### PR DESCRIPTION
**Pull request by SimonDanisch**
Continuation of #3147

### CODE REVIEW

**Comment by tlienart** [comment]
the change to `utils` is not in the right spot (the spot where you made the change is probably a good idea too).

a more general change is maybe something like this:

```
code_lines = split(code, '\n')
ui_lines = map(l -> startswith(l, r"(?:using|import)"), code_lines)
ui_code = join(code_lines[ui_lines], '\n')
rest_code = join(code_lines[.!ui_lines], '\n')
str = """
```julia:example_figure
$ui_code
__result = begin # hide
$rest_code
end # hide
```

(under the assumption that the `using/import` are at the beginning so that this won't change the ordering of code lines). Anyway what you have (just with `using Makie.LaTeXStrings: @L_str`) is probably enough.

**Comment by SimonDanisch** [comment]
> Anyway what you have (just with using Makie.LaTeXStrings: @L_str) is probably enough.

well it doesn't work :(

**Comment by tlienart** [comment]
did you fix the body of examplefigure?

**Comment by SimonDanisch** [comment]
https://github.com/MakieOrg/Makie.jl/blob/bad94df760587de0bb9533345eab722bfb52f1cd/docs/utils.jl#L46
last commit ;)

**Comment by tlienart** [comment]
That's in showhtml, the change should also be in L84-85

**Comment by tlienart** [comment]
yup now the deployment step is happy

**Pull request merged**
