### PR TITLE
Deprecate `rotations` for `rotation` for Scatter and MeshScatter

### PR DESCRIPTION
**Pull request by jkrumbiegel**

### CODE REVIEW

**Comment by jkrumbiegel** [comment]
@SimonDanisch @ffreyer could one of you have a look at the failure in CairoMakie? A Mat4 ends up in a place where it's not expected there, I assume it has something to do with removing the `key"rotations"` conversion methods but I'm not sure.

**Comment by ffreyer** [comment]
> @SimonDanisch @ffreyer could one of you have a look at the failure in CairoMakie? A Mat4 ends up in a place where it's not expected there, I assume it has something to do with removing the `key"rotations"` conversion methods but I'm not sure.

The value got overwritten for meshscatter. should be fixed now.

**Comment by jkrumbiegel** [comment]
Thanks :) some more errors remain but I'll try to dig into those myself

**Comment by jkrumbiegel** [comment]
@SimonDanisch some WGLMakie shader problem remains, I don't know how to fix that. Not sure if `get_rotations` must be `get_rotation`, that also doesn't quite work on my machine

**Pull request merged**
