### PR TITLE
support alpha argument in band()

### PR DESCRIPTION
**Pull request by aplavin**
# Description

The `alpha` argument was just silently ignored before this PR. This makes it actually work.

## Type of change

Delete options that do not apply:

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

**Comment by jkrumbiegel** [comment]
@SimonDanisch is mesh expected to support `alpha`?

**Comment by SimonDanisch** [comment]
This is a CairoMakie issue, so I don't think this is the correct fix.
GLMakie works fine:
```julia
using GLMakie
xs = 1:0.2:10
ys_low = -0.2 .* sin.(xs) .- 0.25
ys_high = 0.2 .* sin.(xs) .+ 0.25

band(xs, ys_low, ys_high, alpha=0.5)
```
image
I'm guessing the problem is in https://github.com/MakieOrg/Makie.jl/blob/master/CairoMakie/src/overrides.jl?

**Comment by jkrumbiegel** [comment]
A right of course, it's just the override that ignores it.

**Comment by SimonDanisch** [comment]
Sorry for the long wait, these overrides are a bit hacky and not that great to review for me, since it's not quite clear to me what the "correct" way of doing things is here.
I think we should just merge this, and clean up the overrides once we support having backends decide which plots are "atomic".
@jkrumbiegel does that sound good?

**Comment by SimonDanisch** [comment]
Thank you!

**Pull request merged**
