### PR TITLE
Clean up list of available formats

### PR DESCRIPTION
**Pull request by jkrumbiegel**
Removes formats we don't support (anymore).

### CODE REVIEW

**Comment by SimonDanisch** [comment]
We still support JPG though!

**Comment by jkrumbiegel** [comment]
Really? I remember removing conversions for that a long time ago in CairoMakie

**Comment by SimonDanisch** [comment]
Yup, we have a fallback in Makie.jl :D

**Comment by SimonDanisch** [comment]
Should we only remove bmp and leave jpg for now?

**Comment by jkrumbiegel** [comment]
Maybe I'm pedantic in that way, but jpg is just not a good format for thin lines etc., we all know what the block artifacts look like. So I'm not really for keeping it. bmp is ok but just makes huge files.

**Comment by SimonDanisch** [comment]
Well, we don't only offer thin line plots, and it's basically free to offer jpg... So I don't see the harm ;) 
But I guess anyone can still do `save("plot.jpg", colorbuffer(fig))`, so, i guess it could be ok to remove it entirely...

**Comment by jkrumbiegel** [comment]
Yeah, either way, it doesn't matter that much

**Review by SimonDanisch — APPROVED** [review]

**Pull request merged**
