### PR TITLE
Docs version picker

### PR DESCRIPTION
**Pull request by jkrumbiegel**

### CODE REVIEW

**Comment by asinghvi17** [comment]
Documenter emits this file to the root of gh-pages but I haven't figured out how to reference it in the docs yet.

**Comment by jkrumbiegel** [comment]
@asinghvi17 I've added those scripts here https://github.com/MakieOrg/Makie.jl/blob/b9bfa873c2ad540838e791429da7a86f67475291/docs/src/.vitepress/config.mts#L20-L21

The question was just how to turn the information from them into a dropdown menu

**Comment by asinghvi17** [comment]
Thanks, we should probably upstream this to DocumenterVitepress as well once it's updated.

**Comment by jkrumbiegel** [comment]
Yeah sure that would be great!

**Pull request merged**
