### PR TITLE
Add fontconfig-based font search

### PR DESCRIPTION
**Pull request by asinghvi17**
# Description

Continuation of #2602 - adds Fontconfig-based font search to Makie.  Users access this through the `font_family(family::String)` function, which returns Attributes and is documented.

Internally, this works in the following way:

When a font family is constructed, we first search the system using Fontconfig to find all fonts which are applicable.  Then, we try to make sure that we have some kind of regular, bold, italic and bold italic font - mainly by trying to use substitutes (roman and book for regular, oblique for italic, etc).  Then, we return a set of Attributes which is guaranteed to have the four basic font styles used in Makie, if they exist.

I also put this kind of mechanism into the current `to_font` method, and hooked up caching, such that:

```julia
julia> @time to_font("lato", "regular")
  0.002450 seconds (42 allocations: 2.195 KiB)
FTFont (family = Lato, style = Black)

julia> @time to_font("lato", "regular")
  0.000003 seconds (1 allocation: 32 bytes)
FTFont (family = Lato, style = Black)

julia> @time to_font("lato", "regular")
  0.000005 seconds (1 allocation: 32 bytes)
FTFont (family = Lato, style = Black)
```

and `to_font("helvetica bold")` yields `FTFont (family = Helvetica, style = Bold)`, which circumvents the limitations of the previous system.

## Type of change

Delete options that do not apply:

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] Added an entry in NEWS.md (for new features and breaking changes)
- [x] Added or changed relevant sections in the documentation
- [x] Added unit tests for new algorithms, conversion methods, etc.

### CODE REVIEW

**Comment by asinghvi17** [comment]
I have no clue why CI failed here - this is the error message:
```juulia
┌ Warning: Could not find family Up and at 'em!, using TeX Gyre Heros Makie.
│ Additional parameters were Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}().
└ @ Makie ~/work/Makie.jl/Makie.jl/src/fonts.jl:148
Font search: Test Failed at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:671
  Expression: contains_warn(read(fname, String), $(Expr(:escape, "Could not find family Up and at 'em!")))
```

**Comment by SimonDanisch** [comment]
As I said before, can we first concentrate on moving the Fontconfig functionality into Fontconfig? And actually turn it into a package we can depend/rely on?  Fontconfig needs at minimum decent cross platform tests for the functionality we want to rely on here and someone committing to maintain it.
Without that, we can never merge this PR and it will just go stale.

**Comment by asinghvi17** [comment]
I just put Fontconfig through the Clang.jl generator process and it seems to have worked quite well, so it shouldn't be too difficult to wrap all its functionality a little more efficiently.  I also started the process of moving a lot of the code in this PR to Fontconfig, which seems like it shouldn't be terribly difficult.

Will put a PR up on Fontconfig with the results of the refactor.

**Comment by SimonDanisch** [comment]
I'm closing this PR for now, so that it's clear that the work needs to happen in Fontconfig.jl first and foremost!
We can re-open and continue once Fontconfig is a well tested & maintained package.

**Pull request closed without merging**
