### PR TITLE
scroll text if width of Textbox is exceeded

### PR DESCRIPTION
**Pull request by bjarthur**
# Description

Fixes https://github.com/MakieOrg/Makie.jl/issues/4268

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] Added an entry in CHANGELOG.md (for new features and breaking changes)
- [ ] Added unit tests for new algorithms, conversion methods, etc.
- [ ] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

**Comment by bjarthur** [comment]
not sure how to add a test.  happy to do so if someone suggests a way

**Comment by bjarthur** [comment]
again, could i please get a review?  here's demo code and a movie of the amazing new functionality this PR offers to Makie :)

```
julia> using GLMakie

julia> f = Figure()

julia> Textbox(f[1,1], width=100)
```

https://github.com/user-attachments/assets/ff19fe50-c6dd-499c-8fbe-4b9f34b8c8ce

**Review by jkrumbiegel — COMMENTED** [review]
This should have a visual reference test I think. Textbox doesn't have its own one so a new one can be added in figures_and_makielayout.jl. All the branches that currently codecov complains about should be handled there, like one normal textbox, one with text scrolled.

With regards to the implementation, I guess this all could be handled a bit more cleanly by a `translate!` on the text and the cursor plot objects instead of modifying their input args. That would correspond more to the idea of "scrolling", too. I don't really like `textplot.converted[1][] = [Point3f(oldv...` as at some point it gets hard to reason about what influences what. Textbox is already not so easy to understand.

**Comment by bjarthur** [comment]
thanks for the suggestion regarding the implementation!  i have refactored to use `translate` and indeed it is much more understandable.  working on tests...

**Comment by bjarthur** [comment]
i have added visual reference tests, but am having trouble uploading them.  when i click on "Update reference images with selection", a popup appears with a "v0.21.0" tag.  irrespective of whether i stick with that or choose another (e.g. "v0.22.0", or "master") i get an error on the julia REPL.  is this because i don't have write permissions to the required repo?

**Comment by jkrumbiegel** [comment]
Yes you need commit rights to use the reference updater. Contributors can only add new test code which notifies committers in the PR status that new images are needed

**Comment by bjarthur** [comment]
thanks @jkrumbiegel for the info.  let me finish the tests and i'll ping you for another review.

**Comment by bjarthur** [comment]
ready for review again.

codecov must not consider the reference tests as those three lines are definitely used there

**Comment by bjarthur** [comment]
the ReferenceTests report that "Violin plots differently scaled.png" is different.  how could that possibly be?

**Comment by SimonDanisch** [comment]
That's not a problem of the pr ;) we've been updating the reference images and there's likely a Missmatch

**Review by jkrumbiegel — APPROVED** [review]

**Comment by SimonDanisch** [comment]
Thanks :)

**Pull request merged**
