### PR TITLE
Implement point-based converts for complex numbers

### PR DESCRIPTION
**Pull request by asinghvi17**
as discussed in #718.

# Description

Adds converts from:
`Vector{Complex{T}}` -> `Vector{Point2{T}}`
`Vector{Complex{T}}, Vector{Real}` -> `Vector{Point3{T}}` where the second input represents z-value.

## Type of change

Delete options that do not apply:

- [X] New feature (non-breaking change which adds functionality)

## Checklist

- [ ] Added an entry in NEWS.md (for new features and breaking changes)
- [X] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

**Comment by jkrumbiegel** [comment]
Not sure if I like this, to be honest. Although I never really use complex numbers, so I don't suffer the manual conversion. To me, this feels a bit on the convenient side and not the clearly motivated side. For example, one could do the same with Dual numbers, which are also 2-element numbers, but for those it would feel even less appropriate. Not sure, maybe others can chime in.

**Comment by asinghvi17** [comment]
I recently had to do complex numbers in a polar axis, for which I thought it was pretty neat.  Of course you can simply pass `real.(vec), imag.(vec)` but it's nice when plotting to quickly visualize results.

**Comment by jkrumbiegel** [comment]
In Plots, it makes sense to me if the axis labels go to `real` and `imaginary` then, you'll know what happened. But this convert treats complex numbers basically the same as generic points, on the lowest level.

**Comment by SimonDanisch** [comment]
Lets close this for now and maybe revisit once we can change axis labels in a plot!

**Pull request closed without merging**
