### PR TITLE
Release `v0.20.10`

### PR DESCRIPTION
**Pull request by asinghvi17**
# Description

- Update to DelaunayTriangulation v1
- Add a Cairo scatter marker conversion override
- Fix categorical colorbar ticks 

TODO:
- [ ] Update reference images
- [ ] Bump versions

### CODE REVIEW

**Comment by SimonDanisch** [comment]
@DanielVandH you know what this is about?
```
│ Closest candidates are:
│   triangulate(::P; segments, boundary_nodes, weights, IntegerType, EdgeType, TriangleType, EdgesType, TrianglesType, randomise, delete_ghosts, delete_empty_features, try_last_inserted_point, skip_points, num_sample_rule, rng, insertion_order, recompute_representative_points, delete_holes, check_arguments, full_polygon_hierarchy, boundary_enricher, boundary_curves, polygonise_n, coarse_n, enrich) where P got unsupported keyword argument "edges"
```
It comes from tricontourf.md:
```julia
n = 20
angles = range(0, 2pi, length = n+1)[1:end-1]
x = [cos.(angles); 2 .* cos.(angles .+ pi/n)]
y = [sin.(angles); 2 .* sin.(angles .+ pi/n)]
z = (x .- 0.5).^2 + (y .- 0.5).^2 .+ 0.5.*randn.()

inner = [n:-1:1; n] # clockwise inner 
outer = [(n+1):(2n); n+1] # counter-clockwise outer
boundary_nodes = [[outer], [inner]]
points = [x'; y']
tri = triangulate(points; boundary_nodes = boundary_nodes)
f, ax, _ = tricontourf(tri, z;
    axis = (; aspect = 1, title = "Constrained triangulation\nvia DelaunayTriangulation.jl"))
scatter!(x, y, color = z, strokewidth = 1, strokecolor = :black)
f
```

**Comment by DanielVandH** [comment]
Oh, sorry - I forgot about the .md files when making the changes... It needs to be `segments =` instead of `edges =` now.

**Comment by DanielVandH** [comment]
Don't think I can make suggestions to an unchanged file in the PR, so I just made the changes in #3828.

**Comment by DanielVandH** [comment]
Sorry. Can you also change the `get_total_area` in triplot.md to `get_area`?

**Pull request merged**
