### PR TITLE
merge CURRENT_DEFAULT_THEME to scene.theme after empty!

### LINKED ISSUE #2817: axislegend() after empty!(fig) generates error
First path:
```julia
using CairoMakie
xs = range(0, π, length=100)

fig = Figure()
fig[1,1] = Axis(fig)
lines!(xs, sin.(xs), label="sin")
lines!(xs, cos.(xs), label="cos")
axislegend()
display(fig)
```
This generates a figure fine:
legend

However, if I subsequently `empty!(fig)` and attempt to draw the same plots by
```julia
empty!(fig)
fig[1,1] = Axis(fig)
lines!(xs, sin.(xs), label="sin")
lines!(xs, cos.(xs), label="cos")
axislegend()
display(fig)
```
it generates an error during `axislegend()`:
```julia-repl
julia> axislegend()
ERROR: KeyError: key :linewidth not found
Stacktrace:
  [1] getindex(h::Dict{Symbol, Observable}, key::Symbol)
    @ Base ./dict.jl:484
  [2] getindex
    @ ~/.julia/packages/MakieCore/6sckc/src/attributes.jl:91 [inlined]
  [3] theme(x::Scene, key::Symbol)
    @ MakieCore ~/.julia/packages/MakieCore/6sckc/src/recipes.jl:58
  [4] default_attribute_values(#unused#::Type{Legend}, scene::Scene)
    @ Makie ~/.julia/packages/Makie/z1gJs/src/makielayout/blocks.jl:172
  [5] _block(T::Type{Legend}, fig_or_scene::Figure, args::Observable{Vector{Tuple{Union{Nothing, AbstractString}, Vector{LegendEntry}}}}; bbox::Observable{GeometryBasics.HyperRectangle{2, Int64}}, kwargs::Base.Pairs{Symbol, Any, Tuple{Symbol, Symbol, Symbol}, NamedTuple{(:margin, :halign, :valign), Tuple{NTuple{4, Int64}, Symbol, Symbol}}})
    @ Makie ~/.julia/packages/Makie/z1gJs/src/makielayout/blocks.jl:317
  [6] _block
    @ ~/.julia/packages/Makie/z1gJs/src/makielayout/blocks.jl:295 [inlined]
  [7] #_#1099
    @ ~/.julia/packages/Makie/z1gJs/src/makielayout/blocks.jl:276 [inlined]
  [8] Block
    @ ~/.julia/packages/Makie/z1gJs/src/makielayout/blocks.jl:275 [inlined]
  [9] Legend(fig_or_scene::Figure, contents::Vector{AbstractPlot}, labels::Vector{String}, title::Nothing; kwargs::Base.Pairs{Symbol, Any, NTuple{4, Symbol}, NamedTuple{(:bbox, :margin, :halign, :valign), Tuple{Observable{GeometryBasics.HyperRectangle{2, Int64}}, NTuple{4, Int64}, Symbol, Symbol}}})
    @ Makie ~/.julia/packages/Makie/z1gJs/src/makielayout/blocks/legend.jl:485
 [10] Legend(fig_or_scene::Figure, axis::Axis, title::Nothing; merge::Bool, unique::Bool, kwargs::Base.Pairs{Symbol, Any, NTuple{4, Symbol}, NamedTuple{(:bbox, :margin, :halign, :valign), Tuple{Observable{GeometryBasics.HyperRectangle{2, Int64}}, NTuple{4, Int64}, Symbol, Symbol}}})
    @ Makie ~/.julia/packages/Makie/z1gJs/src/makielayout/blocks/legend.jl:541
 [11] Legend
    @ ~/.julia/packages/Makie/z1gJs/src/makielayout/blocks/legend.jl:538 [inlined]
 [12] #axislegend#1744
    @ ~/.julia/packages/Makie/z1gJs/src/makielayout/blocks/legend.jl:606 [inlined]
 [13] axislegend
    @ ~/.julia/packages/Makie/z1gJs/src/makielayout/blocks/legend.jl:605 [inlined]
 [14] #axislegend#1742
    @ ~/.julia/packages/Makie/z1gJs/src/makielayout/blocks/legend.jl:582 [inlined]
 [15] axislegend(ax::Axis)
    @ Makie ~/.julia/packages/Makie/z1gJs/src/makielayout/blocks/legend.jl:582
 [16] axislegend()
    @ Makie ~/.julia/packages/Makie/z1gJs/src/makielayout/blocks/legend.jl:582
 [17] top-level scope
    @ REPL[85]:1
```
Julia and Makie versions:
```julia-repl
julia> VERSION
v"1.9.0-rc1"

(@v1.9) pkg> st -m Makie
Status `~/.julia/environments/v1.9/Manifest.toml`
  [ee78f7c6] Makie v0.19.3

(@v1.9) pkg> st CairoMakie
Status `~/.julia/environments/v1.9/Project.toml`
  [13f3f980] CairoMakie v0.10.3
```
The code used to work in a previous version of Makie, but I haven't verified which version it was.

### PR DESCRIPTION
**Pull request by s-fuerst**
# Description

Fixes #2817 

But i do not know what was the intention to remove the merge! line in the commit https://github.com/MakieOrg/Makie.jl/commit/1fcfa688aea713ce5189de34109589ea934935e4

## Type of change

Delete options that do not apply:

- [ ] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Oh, good catch! I dont remember anymore, but looks like an accident to me!

**Comment by SimonDanisch** [comment]
We should add a test for this, that's how it degraded to begin with...

**Comment by s-fuerst** [comment]
I just detected another regression regarding empty!(::Figure), that is not fixed by this PR. After I called empty! on a figure, the figure doesn't adjust anymore to window size changes.

**Comment by SimonDanisch** [comment]
Hm, that one is harder to fix -.-

**Pull request merged**
