### PR TITLE
[CairoMakie] Special-case multipolygons as well as polygons

### PR DESCRIPTION
**Pull request by asinghvi17**
# Description

Fixes a lot of issues where plots with multipolygons (a) take a long time to save and (b) have a huge file size in vector formats.  This is especially common in geographic plotting.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] Added an entry in NEWS.md (for new features and breaking changes)
- [ ] Added or changed relevant sections in the documentation
- [ ] Added unit tests for new algorithms, conversion methods, etc.
- [ ] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

**Comment by jkrumbiegel** [comment]
Instead of copying this stuff here:

```julia
color = poly.color[]
    if color isa AbstractArray{<:Number}
        color = numbers_to_colors(color, poly)
    elseif color isa String
        # string is erroneously broadcasted as chars otherwise
        color = to_color(color)
    end
    strokecolor = poly.strokecolor[]
    if strokecolor isa AbstractArray{<:Number}
        strokecolor = numbers_to_colors(strokecolor, poly)
    elseif strokecolor isa String
        # string is erroneously broadcasted as chars otherwise
        strokecolor = to_color(strokecolor)
    end
``` 

it should be refactored, it is a remnant of what the code was like before we centralized more of these conversions in Makie.jl

**Comment by asinghvi17** [comment]
Looks like the CI failure was an HTTP timeout, unrelated to the changes made here.  CairoMakie CI also works on 1.6 so I think this is good to merge now.

**Comment by jkrumbiegel** [comment]
I think there should be a `to_color` conversion first and then we continue with the value from that. No `isa`, the drawing variants should be done with methods then.

**Comment by asinghvi17** [comment]
Isn't that what this is doing?  A vector of numbers passed to `color` will reach the backend plotting function as that same vector, so it has to be converted somewhere.  Unless you mean that the functionality should be lifted to some other method, like `to_color(plot, color)`, as a general rule?

**Comment by jkrumbiegel** [comment]
That method already kind of exists and is used that way in the other plot primitives. Using colormap etc automatically

**Comment by asinghvi17** [comment]
Scatter and lines in Cairo basically do the same thing (if color isa Array{Number} then numbers_to_colors(...)), see below:

lines
https://github.com/MakieOrg/Makie.jl/blob/db55264501ffbf68154a6fa4268433c3dde1e0c2/CairoMakie/src/primitives.jl#L33-L35

scatter
https://github.com/MakieOrg/Makie.jl/blob/db55264501ffbf68154a6fa4268433c3dde1e0c2/CairoMakie/src/primitives.jl#L188-L192

so if I understand, basically what you're saying is to remove the special-case from Strings, which I agree with and is what I did.

**Comment by jkrumbiegel** [comment]
I think Simon wanted it more like `color = to_color(primitive)` or maybe `color = to_color(primitive, primitive.color[])` anyway, this was supposed to be handled in Makie and not the backends separately. It's not too big of an issue to continue with the code here, but that would just create even more of what we don't really want. Maybe @SimonDanisch should clarify which mode he prefers.

**Comment by SimonDanisch** [comment]
Had to look at the code to decide, and while figuring out how to do it just fixed it 🤷 https://github.com/MakieOrg/Makie.jl/pull/2599

**Pull request closed without merging**
